"""Coherent, bounded corpus snapshots built from exact authoritative bytes."""
from __future__ import annotations

import contextlib
import hashlib
import json
import os
import re
import stat
import time
import unicodedata
from bisect import bisect_left
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from datetime import date, datetime, timezone
from datetime import time as datetime_time
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any

import yaml
from bounded_io import (
    MAX_KNOWLEDGE_PAGE_BYTES,
    SourceChangedDuringRead,
    read_stable_bytes,
)
from code_languages import language_for_path
from page_status import is_retired
from vault_editorial import EDITORIAL_NAMES

COLLECTOR_VERSION = "corpus-collector/v1"
# The name of the rule that cuts a source into chunks. Change where anything is cut
# and this moves with it: deep validation, the doctor and the nightly all ask whether a
# generation was made by today's rule by reading this string. v4 (2026-09-17) names the
# 2026-09-16 rule — a user turn begins its own chunk — which had shipped under v3.
# `tests/test_a_chunker_that_changes_changes_its_version.py` holds the pin. See
# `docs/research/2026-09-17-a-chunker-that-changes-changes-its-version.md`.
# v5 (2026-09-25): a note's claims ledger is no longer a chunk (`_is_claim_ledger`).
EXTRACTOR_VERSION = "markdown-heading-extractor/v5"

MAX_CORPUS_FILES = 10_000
MAX_CORPUS_FILE_BYTES = MAX_KNOWLEDGE_PAGE_BYTES
MAX_CORPUS_TOTAL_BYTES = 64 * 1024 * 1024
MAX_CORPUS_INSPECTED_ENTRIES = 50_000
MAX_CORPUS_DIRECTORIES = 5_000
MAX_CORPUS_DEPTH = 16
MAX_CORPUS_HEADINGS = 100_000
MAX_CORPUS_CHUNKS = 100_000
# Default wall-clock budget for one corpus collection (`collect_corpus`).
DEFAULT_DEADLINE_SECONDS = 30.0

# The claim pages of a project. The journal — one checkpoint event per line, the
# event log no claim reader consults — is kept on disk, consolidated nightly and
# greppable, but not indexed: on the live vault of 2026-09-23 it was 94 % of the
# generation's bytes and most of the reranker's time. See
# `docs/research/2026-09-23-the-corpus-is-the-claim-pages-and-a-project-is-a-project.md`.
PROJECT_FILES = frozenset({"state.md", "context.md"})
# What counts as a code-shaped path (provenance, repository policies). Not
# what the vault's own generation indexes: that is `VAULT_CODE_ROOTS`.
APPROVED_CODE_ROOTS = frozenset(
    {"benchmark", "docs", "integrations", "rules", "scripts", "skills", "tests"}
)
# The vault's generation holds memory — `knowledge/` — and nothing of the
# checkout's own code or documents (issue #29.2: 92 % of an installed vault's
# chunks were this product's tests and docs, outranking the user's pages).
# Code is indexed per repository through `repository_index`, the checkout
# included when its owner asks. One tuple, read by the builder, the freshness
# probe and the grounded-answer snapshot, so the three cannot disagree.
VAULT_CODE_ROOTS: tuple[str, ...] = ()
ARCHIVE_DIRECTORIES = frozenset({"archive", ".archive", "_archive"})
# `__pycache__` holds generated bytecode, never a source, and every repository
# that has run Python once has one under its code roots. This is a fact about
# repositories, so it travels to every one of them.
GENERATED_DIRECTORIES = frozenset({"__pycache__"})
# These three are *this vault's* nouns, not facts about repositories: `gaps` is
# an OKF page type, `_template` is a project scaffold, `raw-sources` is a
# knowledge directory. Applying them inside another repository's code would
# lose a directory of that name with no refusal and no line in the receipt --
# the silence of NEW-67 and NEW-135. So they prune only the walks that read
# this vault's knowledge tree. See the 2026-08-29 note.
VAULT_SKIP_DIRECTORIES = frozenset({"_template", "gaps", "raw-sources"})
_HEADING = re.compile(
    rb"(?m)^[ \t]{0,3}(#{1,6})(?:[ \t]+([^\r\n]*?)|[ \t]*)(?:\r?\n|$)"
)
_FENCE = re.compile(rb"^[ ]{0,3}(`{3,}|~{3,})([^\r\n]*)$")
_CLOSING_HASHES = re.compile(r"[ \t]+#+[ \t]*$")
# The opening of a note's claims ledger, as `claims.CLAIM_LEDGER_RE` reads it.
_CLAIM_LEDGER_OPENING = re.compile(rb"## Claims[ \t]*\r?\n```json[ \t]*\r?\n")
_CYRILLIC = re.compile(r"[\u0400-\u04ff]")
_HAN = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")
_LATIN = re.compile(r"[A-Za-z]")


_POLICY_BOUNDS = {
    "roots": (1, 128),
    "include_globs": (1, 256),
    "ignore_globs": (0, 256),
    "suffixes": (1, 128),
}


def _bounded_nfc_text(value: object, limit: int) -> bool:
    if not isinstance(value, str) or not value:
        return False
    return len(value) <= limit and value == unicodedata.normalize("NFC", value)


def _normalized_text(value: str, limit: int) -> bool:
    if not _bounded_nfc_text(value, limit):
        return False
    return "\\" not in value


def _relative_parts_ok(pure: PurePosixPath) -> bool:
    if pure.is_absolute():
        return False
    return not any(part in {"", ".", ".."} for part in pure.parts)


def _normalized_values(name: str, values: tuple[str, ...]) -> tuple[str, ...]:
    nfc_values = tuple(unicodedata.normalize("NFC", value) for value in values)
    if len(set(nfc_values)) < len(set(values)):
        raise ValueError(f"{name} contains a Unicode normalization collision")
    if name == "suffixes":
        return tuple(value.casefold() for value in nfc_values)
    return nfc_values


def _require_manifest_versions(collector_version: object, extractor_version: object) -> None:
    if not isinstance(collector_version, str) or not collector_version:
        raise ValueError("collector_version must be a non-empty string")
    if not isinstance(extractor_version, str) or not extractor_version:
        raise ValueError("extractor_version must be a non-empty string")


def _require_unique_manifest_entries(entries: list[dict[str, str]]) -> None:
    paths = [entry["relative_path"] for entry in entries]
    logical_ids = [entry["logical_id"] for entry in entries]
    if len(paths) != len(set(paths)) or len(logical_ids) != len(set(logical_ids)):
        raise ValueError("canonical source membership paths and logical IDs must be unique")


def _require_safe_entry(path: Path, info: os.stat_result, *, symlink: bool) -> None:
    reparse = bool(
        (getattr(info, "st_file_attributes", 0) or 0)
        & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    )
    if symlink or reparse:
        raise PermissionError(f"unsafe corpus path: {path}")


class CorpusChanged(RuntimeError):
    """Live corpus membership or content differs from a captured snapshot."""


@dataclass(frozen=True, slots=True)
class SourceMetadata:
    type: str
    project: str | None = None
    authority: str | None = None
    confidence: str | None = None
    status: str = "active"
    valid_from: str | None = None
    valid_to: str | None = None
    language: str | None = None

    @property
    def source_authority(self) -> str | None:
        return self.authority


@dataclass(frozen=True, slots=True)
class SourceRecord:
    logical_id: str
    relative_path: str
    sha256: str
    size: int
    media_type: str
    language: str | None
    git_oid: str | None


@dataclass(frozen=True, slots=True)
class CapturedSource:
    record: SourceRecord
    metadata: SourceMetadata
    content: bytes

    @property
    def captured_bytes(self) -> bytes:
        return self.content


@dataclass(frozen=True, slots=True)
class RetrievalChunk:
    id: str
    source_id: str
    source_path: str
    parent_page: str
    heading_ancestry: tuple[str, ...]
    byte_start: int
    byte_end: int
    line_start: int
    line_end: int
    text: str
    source_sha256: str
    span_sha256: str
    type: str
    project: str | None
    authority: str | None
    confidence: str | None
    status: str
    valid_from: str | None
    valid_to: str | None
    language: str | None

    @property
    def chunk_id(self) -> str:
        return self.id

    @property
    def source_hash(self) -> str:
        return self.source_sha256


@dataclass(frozen=True, slots=True)
class SnapshotPolicy:
    daily_paths: tuple[str, ...]
    code_roots: tuple[str, ...]
    include_historical: bool
    as_of: str | None
    max_files: int
    max_file_bytes: int
    max_total_bytes: int
    max_entries: int
    max_directories: int
    max_depth: int


@dataclass(frozen=True, slots=True)
class CorpusSnapshot:
    sources: tuple[CapturedSource, ...]
    chunks: tuple[RetrievalChunk, ...]
    corpus_sha256: str
    policy: SnapshotPolicy
    collector_version: str = COLLECTOR_VERSION
    extractor_version: str = EXTRACTOR_VERSION

    @property
    def source_hashes(self) -> tuple[tuple[str, str], ...]:
        return tuple(
            (source.record.relative_path, source.record.sha256)
            for source in self.sources
        )


@dataclass(frozen=True, slots=True)
class _Candidate:
    path: Path
    relative: str
    kind: str
    project: str | None
    seal: tuple[_PathIdentity, ...]
    content: bytes | None = None


@dataclass(frozen=True, slots=True)
class _PathIdentity:
    path: Path
    device: int
    inode: int
    mode: int
    size: int
    ctime_ns: int
    attributes: int


def _sha256(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def _canonical_hash(value: object) -> str:
    encoded = json.dumps(
        value, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return _sha256(encoded)


def canonical_chunk_id(
    *,
    source_id: str,
    source_path: str,
    byte_start: int,
    byte_end: int,
    span_sha256: str,
    extractor_version: str = EXTRACTOR_VERSION,
) -> str:
    """Return the shared content-bound identity for one retrieval chunk."""
    return _canonical_hash(
        {
            "extractor": extractor_version,
            "parent": source_id,
            "path": source_path,
            "range": [byte_start, byte_end],
            "sha256": span_sha256,
        }
    )


def _require_closed_source_mapping(record: object) -> Mapping[str, object]:
    if not isinstance(record, Mapping):
        raise TypeError("canonical source manifest entries must be SourceRecord values or objects")
    if set(record) != {"logical_id", "relative_path", "sha256"}:
        raise ValueError("canonical source manifest entries must be closed objects")
    return record


def _manifest_source_fields(
    record: SourceRecord | Mapping[str, object],
) -> tuple[object, object, object]:
    if isinstance(record, SourceRecord):
        return record.logical_id, record.relative_path, record.sha256
    mapping = _require_closed_source_mapping(record)
    return mapping["logical_id"], mapping["relative_path"], mapping["sha256"]


def _bounded_manifest_string(value: object) -> bool:
    return isinstance(value, str) and bool(value) and len(value) <= 4096


def _require_manifest_string(value: object, field: str) -> None:
    if _bounded_manifest_string(value):
        return
    raise ValueError(f"canonical source {field} must be a bounded non-empty string")


def _require_manifest_digest(digest: object) -> None:
    if isinstance(digest, str) and re.fullmatch(r"[0-9a-f]{64}", digest) is not None:
        return
    raise ValueError("canonical source sha256 must be a lowercase SHA-256 digest")


def _manifest_source(record: SourceRecord | Mapping[str, object]) -> dict[str, str]:
    logical_id, relative_path, digest = _manifest_source_fields(record)
    _require_manifest_string(logical_id, "logical_id")
    _require_manifest_string(relative_path, "relative_path")
    _require_manifest_digest(digest)
    return {"relative_path": relative_path, "sha256": digest, "logical_id": logical_id}


def _require_closed_policy_mapping(policy: object) -> Mapping[str, object]:
    if not isinstance(policy, Mapping):
        raise TypeError("canonical source manifest policy must be SnapshotPolicy or an object")
    if set(policy) != {"daily_paths", "code_roots", "include_historical", "as_of"}:
        raise ValueError("canonical source manifest policy must be a closed object")
    return policy


def _policy_manifest_fields(
    policy: SnapshotPolicy | Mapping[str, object],
) -> tuple[object, object, object, object]:
    if isinstance(policy, SnapshotPolicy):
        return policy.daily_paths, policy.code_roots, policy.include_historical, policy.as_of
    mapping = _require_closed_policy_mapping(policy)
    return (
        mapping["daily_paths"],
        mapping["code_roots"],
        mapping["include_historical"],
        mapping["as_of"],
    )


def _string_sequence(value: object) -> bool:
    if not isinstance(value, (list, tuple)):
        return False
    return all(isinstance(item, str) for item in value)


def _require_manifest_flags(include_historical: object, as_of: object) -> None:
    if not isinstance(include_historical, bool):
        raise ValueError("canonical include_historical must be boolean")
    if as_of is not None and not isinstance(as_of, str):
        raise ValueError("canonical as_of must be null or a string")


def _manifest_policy(policy: SnapshotPolicy | Mapping[str, object]) -> dict[str, object]:
    daily_paths, code_roots, include_historical, as_of = _policy_manifest_fields(policy)
    if not _string_sequence(daily_paths):
        raise ValueError("canonical daily_paths must be an array of strings")
    if not _string_sequence(code_roots):
        raise ValueError("canonical code_roots must be an array of strings")
    _require_manifest_flags(include_historical, as_of)
    return {
        "daily_paths": list(daily_paths),
        "code_roots": list(code_roots),
        "include_historical": include_historical,
        "as_of": as_of,
    }


def canonical_source_manifest(
    sources: Iterable[SourceRecord | Mapping[str, object]],
    policy: SnapshotPolicy | Mapping[str, object],
    *,
    collector_version: str = COLLECTOR_VERSION,
    extractor_version: str = EXTRACTOR_VERSION,
) -> dict[str, object]:
    """Return the one canonical source manifest shared by every generation consumer."""
    _require_manifest_versions(collector_version, extractor_version)
    entries = sorted(
        (_manifest_source(source) for source in sources),
        key=lambda item: (item["relative_path"], item["logical_id"]),
    )
    _require_unique_manifest_entries(entries)
    return {
        "collector": collector_version,
        "extractor": extractor_version,
        "policy": _manifest_policy(policy),
        "sources": entries,
    }


def canonical_source_manifest_sha256(
    sources: Iterable[SourceRecord | Mapping[str, object]],
    policy: SnapshotPolicy | Mapping[str, object],
    *,
    collector_version: str = COLLECTOR_VERSION,
    extractor_version: str = EXTRACTOR_VERSION,
) -> str:
    """Hash the shared canonical source manifest."""
    return _canonical_hash(
        canonical_source_manifest(
            sources,
            policy,
            collector_version=collector_version,
            extractor_version=extractor_version,
        )
    )


def _require_manifest_sources(value: Mapping[str, object]) -> list:
    sources = value["sources"]
    if not isinstance(sources, list):
        raise ValueError("canonical source manifest sources must be an array")
    return sources


def _require_closed_manifest(value: object) -> Mapping[str, object]:
    closed = isinstance(value, Mapping) and set(value) == {
        "collector",
        "extractor",
        "policy",
        "sources",
    }
    if not closed:
        raise ValueError("canonical source manifest must be a closed object")
    return value


def validate_canonical_source_manifest(value: object) -> dict[str, object]:
    """Validate and normalize one closed shared canonical source manifest."""
    manifest = _require_closed_manifest(value)
    normalized = canonical_source_manifest(
        _require_manifest_sources(manifest),
        manifest["policy"],
        collector_version=manifest["collector"],
        extractor_version=manifest["extractor"],
    )
    if manifest != normalized:
        raise ValueError("canonical source manifest must use deterministic source ordering")
    return normalized


def _positive_limit(value: object, name: str, *, allow_zero: bool = False) -> int:
    minimum = 0 if allow_zero else 1
    if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
        raise ValueError(f"{name} must be an integer >= {minimum}")
    return value


def _require_monotonic(deadline: object) -> float:
    if isinstance(deadline, bool) or not isinstance(deadline, (int, float)):
        raise ValueError("deadline must be a monotonic timestamp")
    return float(deadline)


def _require_seconds(value: object) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)) or value < 0:
        raise ValueError("deadline_seconds must be non-negative")
    return float(value)


def _deadline_value(deadline: float | None, deadline_seconds: float | None) -> float:
    if deadline is not None and deadline_seconds is not None:
        raise ValueError("deadline and deadline_seconds are mutually exclusive")
    if deadline is not None:
        return _require_monotonic(deadline)
    seconds = DEFAULT_DEADLINE_SECONDS if deadline_seconds is None else deadline_seconds
    return time.monotonic() + _require_seconds(seconds)


def _check_deadline(deadline: float) -> None:
    if time.monotonic() >= deadline:
        raise TimeoutError("corpus collection deadline reached")


def _check_processing_stop(
    deadline: float | None, cancelled: Callable[[], bool] | None
) -> None:
    if bool(cancelled and cancelled()):
        raise TimeoutError("corpus collection cancelled")
    if deadline is not None:
        _check_deadline(deadline)


def _under_prefix(normalized: str, prefixes: tuple[str, ...]) -> bool:
    return any(
        normalized == prefix or normalized.startswith(prefix + "/") for prefix in prefixes
    )


def _valid_source_path(raw: str, pure: PurePosixPath, normalized: str) -> bool:
    if not raw or "\\" in raw:
        return False
    if normalized != raw:
        return False
    return _relative_parts_ok(pure)


def _relative_posix(value: str | Path, *, prefixes: tuple[str, ...]) -> str:
    raw = str(value)
    pure = PurePosixPath(raw)
    normalized = unicodedata.normalize("NFC", pure.as_posix())
    if not _valid_source_path(raw, pure, normalized) or not _under_prefix(normalized, prefixes):
        raise ValueError("source path must be a normalized relative POSIX path")
    return normalized


def _windows_shaped(raw: str) -> bool:
    windows_path = PureWindowsPath(raw)
    return "\\" in raw or ":" in raw or bool(windows_path.drive or windows_path.root)


_CODE_ROOT_ERROR = "code root must be a normalized approved relative POSIX path"


def always_pruned_directory_name(name: str) -> bool:
    """Pruned in every repository: generated bytecode, and anything hidden.

    Hidden is the one that carries weight -- `.claude/worktrees/` is a whole
    second copy of the repository, the defect closed in commit 1d06e6a. The
    workspace revision walks by this rule too, so the freshness proof covers
    what the corpus covers and no more. See
    `docs/research/2026-09-17-a-revision-walks-what-the-corpus-walks.md`.
    """
    return name in GENERATED_DIRECTORIES or name.startswith(".")


def _pruned_directory_name(
    name: str, *, include_archives: bool, vault_vocabulary: bool = True
) -> bool:
    """Whether the corpus walk refuses to descend into a directory of this name.

    One definition, shared by the walk and by :func:`collectable_root_name`,
    because a code root the walk would prune collects nothing and a root that
    silently collects nothing is NEW-67 with extra steps.

    `vault_vocabulary` is what does *not* travel: the caller says whether this
    walk is reading this vault's knowledge tree, where `gaps` and `_template`
    are page types, or somebody's code, where they are just directory names.
    """
    if always_pruned_directory_name(name):
        return True
    if vault_vocabulary and name in VAULT_SKIP_DIRECTORIES:
        return True
    return name in ARCHIVE_DIRECTORIES and not include_archives


def collectable_root_name(name: str) -> bool:
    """Whether this top-level directory name can be a code root at all.

    Two conditions, and neither of them is about *this* vault's layout: the
    name must be a normalized relative POSIX component, and it must not be one
    the walk prunes. Hidden is the one that bites in practice --
    `_add_code_root` hands the root itself to the walk, which applies the prune
    rule only to children, so `.claude` as a code root would walk
    `.claude/worktrees/`, a whole second copy of the repository. That is the
    defect closed in commit 1d06e6a, where the workspace call graph walked
    7,261 files of 7,686.
    """
    try:
        normalized = _relative_posix(name, prefixes=(str(name),))
    except ValueError:
        return False
    if len(PurePosixPath(normalized).parts) != 1:
        return False
    return not _pruned_directory_name(
        normalized, include_archives=False, vault_vocabulary=False
    )


def _normalized_code_root(value: str | Path, approved: tuple[str, ...]) -> str:
    try:
        return _relative_posix(value, prefixes=approved)
    except ValueError as exc:
        raise ValueError(_CODE_ROOT_ERROR) from exc


def _require_collectable_root(normalized: str) -> None:
    top = PurePosixPath(normalized).parts[0]
    if _pruned_directory_name(top, include_archives=False, vault_vocabulary=False):
        raise ValueError(f"code root is a directory the corpus walk prunes: {top}")


def _code_root(value: str | Path, approved: tuple[str, ...]) -> str:
    """One code root, normalized against the *caller's* allowlist.

    The name allowlist belongs to the caller: this vault passes its own
    `APPROVED_CODE_ROOTS`, and `repository_index` passes the top-level
    directories Git tracks in the repository it was pointed at. What does not
    belong to the caller is the shape -- relative, POSIX, NFC-normalized, no
    traversal, no drive -- and whether the walk would prune it.
    """
    raw = str(value)
    if _windows_shaped(raw):
        raise ValueError(_CODE_ROOT_ERROR)
    normalized = _normalized_code_root(value, approved)
    _require_collectable_root(normalized)
    return normalized


def _safe_info(path: Path) -> os.stat_result:
    info = path.lstat()
    if path.is_symlink() or bool(
        getattr(info, "st_file_attributes", 0)
        & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    ):
        raise PermissionError(f"unsafe corpus path: {path}")
    return info


# Only the two attribute bits that change what an ancestor *is*. Windows sets
# and clears others — indexing, offline, pinning — while a path is being walked,
# and a seal that compares the whole DWORD reads that as a swapped ancestor.
_SEAL_ATTRIBUTES = 0x10 | 0x400  # FILE_ATTRIBUTE_DIRECTORY, _REPARSE_POINT


def _identity(path: Path, info: os.stat_result) -> _PathIdentity:
    return _PathIdentity(
        path=path,
        device=info.st_dev,
        inode=info.st_ino,
        mode=info.st_mode,
        size=info.st_size,
        ctime_ns=info.st_ctime_ns,
        attributes=(getattr(info, "st_file_attributes", 0) or 0) & _SEAL_ATTRIBUTES,
    )


def _seal_path(
    vault: Path,
    path: Path,
    *,
    target_directory: bool,
    max_components: int,
) -> tuple[_PathIdentity, ...]:
    seal = _build_path_seal(
        vault,
        path,
        target_directory=target_directory,
        max_components=max_components,
    )
    _verify_seal(seal, changed_error=PermissionError)
    return seal


def _seal_source_file(
    vault: Path, path: Path, max_components: int
) -> tuple[_PathIdentity, ...]:
    """The seal of one source read by path: its ancestors, then the file itself.

    An ancestor that moved between the two looks is still a `PermissionError`.
    The file itself moving is somebody writing it, which the descriptor walk
    calls `CorpusChanged`, so this one does too. Research:
    `docs/research/2026-09-17-five-failures-only-the-other-systems-showed.md`.
    """
    seal = _build_path_seal(
        vault, path, target_directory=False, max_components=max_components
    )
    _verify_seal(seal[:-1], changed_error=PermissionError)
    _require_source_as_sealed(seal[-1])
    return seal


def _require_source_as_sealed(expected: _PathIdentity) -> None:
    try:
        current = _identity(expected.path, _safe_info(expected.path))
    except FileNotFoundError as exc:
        raise CorpusChanged(f"corpus source vanished: {expected.path.name}") from exc
    if current != expected:
        raise CorpusChanged(
            f"corpus source changed: {expected.path.name} "
            f"({_identity_delta(expected, current)})"
        )


def _relative_within(vault: Path, path: Path) -> Path:
    try:
        return path.relative_to(vault)
    except ValueError as exc:
        raise PermissionError("corpus path escapes the resolved vault") from exc


def _component_paths(vault: Path, relative: Path) -> list[Path]:
    components = [vault]
    current = vault
    for part in relative.parts:
        current /= part
        components.append(current)
    return components


def _require_component_kind(
    component: Path, info: os.stat_result, *, expect_directory: bool, allow_regular: bool
) -> None:
    if expect_directory != stat.S_ISDIR(info.st_mode):
        expected = "directory" if expect_directory else "regular file"
        raise PermissionError(f"corpus path component must be a {expected}: {component}")
    if allow_regular and not stat.S_ISREG(info.st_mode):
        raise PermissionError(f"corpus source must be a regular file: {component}")


def _require_inside(component: Path, vault: Path) -> None:
    try:
        component.resolve(strict=True).relative_to(vault)
    except ValueError as exc:
        raise PermissionError("corpus path resolves outside the vault") from exc


def _sealed_component(
    component: Path, vault: Path, *, is_target: bool, target_directory: bool
) -> _PathIdentity:
    info = _safe_info(component)
    expect_directory = not is_target or target_directory
    _require_component_kind(
        component,
        info,
        expect_directory=expect_directory,
        allow_regular=is_target and not target_directory,
    )
    _require_inside(component, vault)
    return _identity(component, info)


def _build_path_seal(
    vault: Path,
    path: Path,
    *,
    target_directory: bool,
    max_components: int,
) -> tuple[_PathIdentity, ...]:
    relative = _relative_within(vault, path)
    if len(relative.parts) > max_components:
        raise ValueError("corpus ancestor depth limit exceeded")
    components = _component_paths(vault, relative)
    last = len(components) - 1
    return tuple(
        _sealed_component(
            component,
            vault,
            is_target=index == last,
            target_directory=target_directory,
        )
        for index, component in enumerate(components)
    )


def _open_sealed_posix_path(
    vault: Path,
    path: Path,
    *,
    target_directory: bool,
    max_components: int,
) -> tuple[tuple[_PathIdentity, ...], int]:
    seal = _build_path_seal(
        vault,
        path,
        target_directory=target_directory,
        max_components=max_components,
    )
    descriptor = _open_descriptor_chain(seal, changed_error=PermissionError)
    return seal, descriptor


def _identity_delta(expected: _PathIdentity, current: _PathIdentity) -> str:
    """Name the fields that moved, so the refusal can be acted on."""
    fields = ("device", "inode", "mode", "size", "ctime_ns", "attributes")
    changed = [
        f"{name}: {getattr(expected, name)} -> {getattr(current, name)}"
        for name in fields
        if getattr(expected, name) != getattr(current, name)
    ]
    return ", ".join(changed) or "identical fields"


def _verify_seal(
    seal: tuple[_PathIdentity, ...], *, changed_error: type[Exception] = CorpusChanged
) -> None:
    for expected in seal:
        try:
            current = _identity(expected.path, _safe_info(expected.path))
        except (OSError, PermissionError) as exc:
            raise changed_error(f"corpus ancestor changed: {expected.path}") from exc
        if current != expected:
            raise changed_error(
                f"corpus ancestor changed: {expected.path} ({_identity_delta(expected, current)})"
            )
    _verify_descriptor_chain(seal, changed_error=changed_error)


def _verify_descriptor_chain(
    seal: tuple[_PathIdentity, ...], *, changed_error: type[Exception]
) -> None:
    if os.name != "posix" or not seal:
        return
    descriptor = _open_descriptor_chain(seal, changed_error=changed_error)
    os.close(descriptor)


def _child_descriptor_flags(expected: _PathIdentity, flags: int) -> int:
    if stat.S_ISDIR(expected.mode):
        return flags | getattr(os, "O_DIRECTORY", 0)
    return flags


def _open_sealed_root(expected: _PathIdentity, flags: int, changed_error) -> int:
    descriptor = os.open(expected.path, flags | getattr(os, "O_DIRECTORY", 0))
    if _identity(expected.path, os.fstat(descriptor)) != expected:
        os.close(descriptor)
        raise changed_error(f"corpus ancestor changed: {expected.path}")
    return descriptor


def _descend(descriptor: int, expected: _PathIdentity, flags: int, changed_error) -> int:
    """Open the next component; the descriptor handed in is closed either way."""
    try:
        child = os.open(
            expected.path.name, _child_descriptor_flags(expected, flags), dir_fd=descriptor
        )
    finally:
        os.close(descriptor)
    if _identity(expected.path, os.fstat(child)) != expected:
        os.close(child)
        raise changed_error(f"corpus ancestor changed: {expected.path}")
    return child


def _open_descriptor_chain(
    seal: tuple[_PathIdentity, ...], *, changed_error: type[Exception]
) -> int:
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    descriptor = -1
    try:
        descriptor = _open_sealed_root(seal[0], flags, changed_error)
        for expected in seal[1:]:
            handed, descriptor = descriptor, -1
            descriptor = _descend(handed, expected, flags, changed_error)
        result = descriptor
        descriptor = -1
        return result
    except OSError as exc:
        raise changed_error("corpus ancestor changed during descriptor traversal") from exc
    finally:
        if descriptor >= 0:
            os.close(descriptor)


def _same_opened_object(left: os.stat_result, right: os.stat_result) -> bool:
    return (
        left.st_dev,
        left.st_ino,
        left.st_mode,
        left.st_size,
        left.st_mtime_ns,
        left.st_ctime_ns,
    ) == (
        right.st_dev,
        right.st_ino,
        right.st_mode,
        right.st_size,
        right.st_mtime_ns,
        right.st_ctime_ns,
    )


def _same_descriptor_identity(left: os.stat_result, right: os.stat_result) -> bool:
    return (left.st_dev, left.st_ino, stat.S_IFMT(left.st_mode)) == (
        right.st_dev,
        right.st_ino,
        stat.S_IFMT(right.st_mode),
    )


def _descriptor_flags(*, directory: bool) -> int:
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    if directory:
        flags |= getattr(os, "O_DIRECTORY", 0)
    return flags


def _require_bounded_size(size: int, max_bytes: int) -> None:
    if size > max_bytes:
        raise ValueError(f"corpus source exceeds {max_bytes} bytes")


def _read_chunks(descriptor: int, max_bytes: int) -> bytes:
    chunks: list[bytes] = []
    remaining = max_bytes + 1
    while remaining:
        chunk = os.read(descriptor, min(remaining, 1024 * 1024))
        if not chunk:
            break
        chunks.append(chunk)
        remaining -= len(chunk)
    return b"".join(chunks)


def _read_bounded_descriptor(descriptor: int, max_bytes: int) -> bytes:
    before = os.fstat(descriptor)
    if not stat.S_ISREG(before.st_mode):
        raise PermissionError("corpus source descriptor must be a regular file")
    _require_bounded_size(before.st_size, max_bytes)
    content = _read_chunks(descriptor, max_bytes)
    _require_bounded_size(len(content), max_bytes)
    if not _same_opened_object(before, os.fstat(descriptor)):
        raise CorpusChanged("corpus source changed during descriptor read")
    return content


def _opened_listed_entry(name: str, descriptor: int, *, directory: bool) -> int:
    """Open one entry the listing named; one that has gone is a changed corpus.

    A file deleted between the listing and the open is the tree moving under the
    walk, which is what `CorpusChanged` means and what `collect_corpus` retries.
    Left as a bare `FileNotFoundError` it reached `repository_index` as "this
    repository exceeds the corpus bounds", which is neither true nor actionable.
    See `docs/research/2026-09-17-a-file-that-vanishes-mid-walk-is-a-changed-corpus.md`.
    """
    try:
        return os.open(name, _descriptor_flags(directory=directory), dir_fd=descriptor)
    except FileNotFoundError as exc:
        raise CorpusChanged(f"corpus entry vanished before open: {name}") from exc


class _Discovery:
    def __init__(
        self,
        vault: Path,
        *,
        max_files: int,
        max_entries: int,
        max_directories: int,
        max_depth: int,
        max_file_bytes: int,
        max_total_bytes: int,
        deadline: float,
        include_archives: bool,
    ) -> None:
        self.vault = vault
        self.max_files = max_files
        self.max_entries = max_entries
        self.max_directories = max_directories
        self.max_depth = max_depth
        self.max_file_bytes = max_file_bytes
        self.max_total_bytes = max_total_bytes
        self.deadline = deadline
        self.include_archives = include_archives
        self.entries = 0
        self.directories = 0
        self.total_bytes = 0
        self.candidates: dict[str, _Candidate] = {}

    def add(self, path: Path, kind: str, project: str | None = None) -> None:
        _check_deadline(self.deadline)
        if os.name == "posix":
            _, descriptor = _open_sealed_posix_path(
                self.vault,
                path,
                target_directory=False,
                max_components=self.max_depth + 3,
            )
            try:
                content = _read_bounded_descriptor(descriptor, self.max_file_bytes)
            finally:
                os.close(descriptor)
            self._store(path, kind, project, (), content)
            return
        seal = _seal_source_file(self.vault, path, self.max_depth + 3)
        self._store(path, kind, project, seal, None)

    def _store(
        self,
        path: Path,
        kind: str,
        project: str | None,
        seal: tuple[_PathIdentity, ...],
        content: bytes | None,
    ) -> None:
        relative = unicodedata.normalize("NFC", path.relative_to(self.vault).as_posix())
        if not _storable_source_path(relative):
            return
        self._require_unseen(relative)
        self._count_bytes(content)
        self.candidates[relative] = _Candidate(path, relative, kind, project, seal, content)
        if len(self.candidates) > self.max_files:
            raise ValueError("corpus file limit exceeded")

    def _require_unseen(self, relative: str) -> None:
        if relative in self.candidates:
            raise ValueError(f"duplicate corpus source path: {relative}")

    def _count_bytes(self, content: bytes | None) -> None:
        if content is None:
            return
        self.total_bytes += len(content)
        if self.total_bytes > self.max_total_bytes:
            raise ValueError("corpus total byte limit exceeded")

    def walk(self, root: Path, kind: str) -> None:
        if not root.exists():
            return
        if os.name == "posix":
            self._walk_posix(root, kind)
            return
        self._walk_windows(root, kind)

    def _directory_seal(self, path: Path) -> tuple[_PathIdentity, ...]:
        return _seal_path(
            self.vault,
            path,
            target_directory=True,
            max_components=self.max_depth + 3,
        )

    def _count_directory(self, depth: int) -> None:
        self.directories += 1
        if self.directories > self.max_directories:
            raise ValueError("corpus directory limit exceeded")
        if depth > self.max_depth:
            raise ValueError("corpus depth limit exceeded")

    def _count_entry(self) -> None:
        self.entries += 1
        if self.entries > self.max_entries:
            raise ValueError("corpus traversal entry limit exceeded")

    def _directory_excluded(self, name: str, kind: str) -> bool:
        """`kind == "code"` means somebody's source tree, so vault nouns do not apply."""
        return _pruned_directory_name(
            name,
            include_archives=self.include_archives,
            vault_vocabulary=kind != "code",
        )

    @staticmethod
    def _project_of(path: Path, root: Path, kind: str) -> str | None:
        if kind != "project":
            return None
        parts = path.relative_to(root).parts
        if len(parts) > 1:
            return parts[0]
        return None

    def _walk_windows(self, root: Path, kind: str) -> None:
        stack = [(root, 0, self._directory_seal(root))]
        while stack:
            current, depth, current_seal = stack.pop()
            children = self._walk_windows_directory(root, current, depth, current_seal, kind)
            stack.extend((child, depth + 1, seal) for child, seal in reversed(children))

    def _windows_entries(self, current: Path) -> list:
        entries = []
        with os.scandir(current) as iterator:
            for entry in iterator:
                _check_deadline(self.deadline)
                self._count_entry()
                entries.append(entry)
        return entries

    def _walk_windows_directory(
        self,
        root: Path,
        current: Path,
        depth: int,
        current_seal: tuple[_PathIdentity, ...],
        kind: str,
    ) -> list:
        _check_deadline(self.deadline)
        _verify_seal(current_seal)
        self._count_directory(depth)
        entries = self._windows_entries(current)
        _verify_seal(current_seal)
        children = [
            child
            for child in (
                self._windows_entry(root, entry, depth, kind)
                for entry in sorted(entries, key=lambda item: item.name)
            )
            if child is not None
        ]
        _verify_seal(current_seal)
        return children

    def _windows_entry(self, root: Path, entry: os.DirEntry, depth: int, kind: str):
        """The child directory to descend into, or None once the file is stored."""
        _check_deadline(self.deadline)
        path = Path(entry.path)
        info = self._entry_info(entry)
        _require_safe_entry(path, info, symlink=entry.is_symlink())
        if stat.S_ISDIR(info.st_mode):
            return self._windows_child(path, entry.name, depth, kind)
        if stat.S_ISREG(info.st_mode) and self._eligible(path, kind):
            self.add(path, kind, self._project_of(path, root, kind))
        return None

    def _windows_child(self, path: Path, name: str, depth: int, kind: str):
        if self._directory_excluded(name, kind):
            return None
        if depth >= self.max_depth:
            raise ValueError("corpus depth limit exceeded")
        return (path, self._directory_seal(path))

    def _walk_posix(self, root: Path, kind: str) -> None:
        _, descriptor = _open_sealed_posix_path(
            self.vault,
            root,
            target_directory=True,
            max_components=self.max_depth + 3,
        )
        try:
            self._walk_posix_directory(root, root, 0, descriptor, kind)
        finally:
            os.close(descriptor)

    def _posix_entries(self, descriptor: int) -> list:
        entries = []
        with os.scandir(descriptor) as iterator:
            for entry in iterator:
                _check_deadline(self.deadline)
                self._count_entry()
                entries.append(
                    (
                        entry.name,
                        os.stat(entry.name, dir_fd=descriptor, follow_symlinks=False),
                    )
                )
        return entries

    def _walk_posix_directory(
        self,
        root: Path,
        current: Path,
        depth: int,
        descriptor: int,
        kind: str,
    ) -> None:
        _check_deadline(self.deadline)
        opened_directory = os.fstat(descriptor)
        if not stat.S_ISDIR(opened_directory.st_mode):
            raise PermissionError("corpus traversal descriptor must be a directory")
        self._count_directory(depth)
        entries = self._posix_entries(descriptor)
        if not _same_descriptor_identity(opened_directory, os.fstat(descriptor)):
            raise CorpusChanged("corpus directory descriptor changed during traversal")
        for name, info in sorted(entries, key=lambda item: item[0]):
            self._posix_entry(root, current, depth, descriptor, kind, name, info)

    def _entry_info(self, entry: os.DirEntry) -> os.stat_result:
        """This listed entry's metadata taken now; one that has gone is a changed corpus.

        Not `entry.stat()`. CPython: "On Unix, this method always requires a
        system call. On Windows, it only requires a system call if
        follow_symlinks is True and the entry is a reparse point" — so on
        Windows it answers out of the directory listing, a name deleted since
        the listing still returns metadata, and the walk carries on over a file
        that is not there until an unretryable FileNotFoundError ends the whole
        capture. The POSIX branch already states each listed name itself
        (`_posix_entries`). Research:
        docs/research/2026-09-18-a-listed-entry-is-stated-now-not-remembered.md
        """
        try:
            return os.lstat(entry.path)
        except FileNotFoundError as exc:
            raise CorpusChanged(
                f"corpus entry vanished during the walk: {entry.name}"
            ) from exc

    def _posix_entry(
        self,
        root: Path,
        current: Path,
        depth: int,
        descriptor: int,
        kind: str,
        name: str,
        info: os.stat_result,
    ) -> None:
        _check_deadline(self.deadline)
        path = current / name
        _require_safe_entry(path, info, symlink=stat.S_ISLNK(info.st_mode))
        if stat.S_ISDIR(info.st_mode):
            self._posix_child(root, path, depth, descriptor, kind, name, info)
            return
        if stat.S_ISREG(info.st_mode) and self._eligible(path, kind):
            self._posix_source(root, path, descriptor, kind, name, info)

    def _posix_child(
        self,
        root: Path,
        path: Path,
        depth: int,
        descriptor: int,
        kind: str,
        name: str,
        info: os.stat_result,
    ) -> None:
        if self._directory_excluded(name, kind):
            return
        if depth >= self.max_depth:
            raise ValueError("corpus depth limit exceeded")
        child = _opened_listed_entry(name, descriptor, directory=True)
        try:
            if not _same_descriptor_identity(info, os.fstat(child)):
                raise CorpusChanged("corpus child directory changed before open")
            self._walk_posix_directory(root, path, depth + 1, child, kind)
        finally:
            os.close(child)

    def _posix_source(
        self,
        root: Path,
        path: Path,
        descriptor: int,
        kind: str,
        name: str,
        info: os.stat_result,
    ) -> None:
        source = _opened_listed_entry(name, descriptor, directory=False)
        try:
            if not _same_opened_object(info, os.fstat(source)):
                raise CorpusChanged("corpus source changed before descriptor open")
            content = _read_bounded_descriptor(source, self.max_file_bytes)
        finally:
            os.close(source)
        self._store(path, kind, self._project_of(path, root, kind), (), content)

    @staticmethod
    def _eligible(path: Path, kind: str) -> bool:
        if kind == "note":
            return path.suffix.casefold() == ".md" and path.name not in EDITORIAL_NAMES
        if kind == "project":
            return path.name in PROJECT_FILES
        return True


def _walk_knowledge(discovery: _Discovery, vault: Path) -> None:
    discovery.walk(vault / "knowledge/notes", "note")
    discovery.walk(vault / "knowledge/projects", "project")
    # Session records are deliberately NOT collected. They are kept verbatim on
    # disk, they are read by the nightly consolidation, and they are greppable —
    # but they are not part of the retrieval corpus, because measurement says
    # they take it over: importing 236 past sessions (about 10 MB of the same
    # conversations the pages were compiled from) moved the vault stand from
    # hit@5 0.7 to 0.0, and neither a below-neutral trust weight nor ordering
    # compiled pages first brought it back past 0.4 — by then the decision page
    # was no longer in the candidate pool at all.
    #
    # What would make them safe to index is a second tier consulted when the
    # compiled pages do not answer, or a per-source quota in the pool. Neither is
    # built, so the honest state is: kept, not indexed. See MEM-01 in
    # docs/DEVELOPER-AUDIT-STATUS-2026-08-18.md.


def is_memory_path(relative_path: str, code_roots: Iterable[str] = ()) -> bool:
    """True for a source the memory walk collected, false for one a code root holds.

    `knowledge/` is this vault's noun. Another repository's tracked `knowledge/`
    directory is one of its code roots, and `knowledge/mod.py` there is code. The
    vault's own code roots never include it (`repository_index.selected_code_roots`).
    See `docs/research/2026-09-17-a-question-is-answered-by-its-own-kind-of-generation.md`.
    """
    path = PurePosixPath(relative_path)
    if path.parts[:1] != ("knowledge",):
        return False
    return not any(path.is_relative_to(PurePosixPath(root)) for root in code_roots)


def _walk_memory(discovery: _Discovery, vault: Path, policy: SnapshotPolicy) -> None:
    """The knowledge tree belongs to the memory generation, not to the code one.

    One checkout carries two generations — memory, which the active pointer names, and
    code, which is only registered (`docs/research/2026-09-12-the-vault-is-a-repository-too.md`).
    The code roots already exclude `knowledge`, but this walk added it back: the vault's
    code generation of 2026-09-15 carried all 333 private pages, 28 % of its chunk tokens.
    Research: `docs/research/2026-09-16-the-code-index-leaves-the-knowledge-alone.md`.
    """
    if policy.code_roots:
        return
    _walk_knowledge(discovery, vault)


def _existing_path(vault: Path, relative: str) -> Path:
    path = vault.joinpath(*PurePosixPath(relative).parts)
    if not path.exists():
        raise FileNotFoundError(relative)
    return path


def _add_daily_paths(
    discovery: _Discovery, vault: Path, policy: SnapshotPolicy, deadline: float
) -> None:
    for relative in policy.daily_paths:
        _check_deadline(deadline)
        discovery.add(_existing_path(vault, relative), "daily")


def _add_code_root(discovery: _Discovery, path: Path, relative: str) -> None:
    info = _safe_info(path)
    if stat.S_ISDIR(info.st_mode):
        discovery.walk(path, "code")
        return
    if not stat.S_ISREG(info.st_mode):
        raise PermissionError(f"code root must be a regular path: {relative}")
    discovery.add(path, "code")


def _add_code_roots(
    discovery: _Discovery, vault: Path, policy: SnapshotPolicy, deadline: float
) -> None:
    for relative in policy.code_roots:
        _check_deadline(deadline)
        _add_code_root(discovery, _existing_path(vault, relative), relative)


def _discover(vault: Path, policy: SnapshotPolicy, deadline: float) -> tuple[_Candidate, ...]:
    discovery = _Discovery(
        vault,
        max_files=policy.max_files,
        max_entries=policy.max_entries,
        max_directories=policy.max_directories,
        max_depth=policy.max_depth,
        max_file_bytes=policy.max_file_bytes,
        max_total_bytes=policy.max_total_bytes,
        deadline=deadline,
        include_archives=policy.include_historical or policy.as_of is not None,
    )
    _walk_memory(discovery, vault, policy)
    _add_daily_paths(discovery, vault, policy, deadline)
    _add_code_roots(discovery, vault, policy, deadline)
    return tuple(discovery.candidates[key] for key in sorted(discovery.candidates))


# The graph names a source `source:<relative path>` in at most 512 characters,
# without control characters or backslashes. A file it cannot name is not a
# source, exactly as a binary file is not. See
# `docs/research/2026-09-14-the-rest-of-the-readers-before-the-writer.md`.
_MAX_SOURCE_PATH_CHARS = 512 - len("source:")
_UNNAMEABLE_PATH = re.compile(r"[\x00-\x1f\x7f\\]")


def _storable_source_path(relative: str) -> bool:
    if len(relative) > _MAX_SOURCE_PATH_CHARS:
        return False
    return _UNNAMEABLE_PATH.search(relative) is None


def _decodes_as_utf8(content: bytes) -> bool:
    """Whether these bytes are text at all; a binary file is not a source.

    It is still hashed, so membership checks still see it, but it is left out
    of the corpus. One stray binary under a code root must not be able to fail
    the whole generation.
    """
    try:
        content.decode("utf-8", errors="strict")
    except UnicodeDecodeError:
        return False
    return True


def _line_spans(content: bytes, start: int = 0) -> Iterable[tuple[int, int]]:
    offset = start
    while offset < len(content):
        newline = content.find(b"\n", offset)
        end = len(content) if newline < 0 else newline + 1
        yield offset, end
        offset = end


def _frontmatter_close(
    content: bytes,
    lines,
    deadline: float | None,
    cancelled: Callable[[], bool] | None,
) -> tuple[int, int] | None:
    for line_start, line_end in lines:
        _check_processing_stop(deadline, cancelled)
        if content[line_start:line_end].strip() == b"---":
            return line_start, line_end
    return None


@dataclass(frozen=True, slots=True)
class Frontmatter:
    """A page's metadata block as read, where its body starts, and what was wrong.

    A page whose metadata cannot be read costs its metadata, never the corpus:
    one note with `title: Fix: x` used to make every reader of the vault raise.
    See `docs/research/2026-09-14-one-page-cannot-close-the-vault.md`.
    """

    mapping: dict[str, Any]
    body_start: int
    problem: str | None = None


def _frontmatter_mapping(raw: bytes) -> tuple[dict[str, Any], str | None]:
    try:
        value = yaml.safe_load(raw.decode("utf-8", errors="strict"))
    except (UnicodeDecodeError, yaml.YAMLError) as exc:
        return {}, f"frontmatter is not valid YAML ({type(exc).__name__})"
    if value is None:
        return {}, None
    if not isinstance(value, Mapping):
        return {}, "frontmatter is not a mapping"
    return dict(value), None


def read_frontmatter(
    content: bytes,
    *,
    deadline: float | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> Frontmatter:
    """The one reading of a Markdown page's frontmatter, for every reader."""
    lines = iter(_line_spans(content))
    first = next(lines, None)
    if first is None or content[first[0] : first[1]].strip() != b"---":
        return Frontmatter({}, 0)
    closing = _frontmatter_close(content, lines, deadline, cancelled)
    if closing is None:
        return Frontmatter({}, 0, "unterminated YAML frontmatter")
    mapping, problem = _frontmatter_mapping(content[first[1] : closing[0]])
    return Frontmatter(mapping, closing[1], problem)


def _frontmatter(
    content: bytes,
    *,
    deadline: float | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> tuple[dict[str, Any], int]:
    read = read_frontmatter(content, deadline=deadline, cancelled=cancelled)
    return read.mapping, read.body_start


def _utc_text(value: datetime) -> str:
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def _dated_metadata_text(value: date | datetime) -> str:
    if isinstance(value, datetime):
        return _utc_text(value)
    return value.isoformat()


def _scalar_metadata_text(value: object) -> str | None:
    """A single value as text; a list or mapping in a one-value field is absent."""
    if isinstance(value, (str, int, float, bool)):
        return str(value)
    return None


def _metadata_value(value: object) -> str | None:
    if value is None:
        return None
    if isinstance(value, (date, datetime)):
        return _dated_metadata_text(value)
    return _scalar_metadata_text(value)


_DEFAULT_SOURCE_TYPES = {
    "note": "note",
    "daily": "daily-evidence",
    "session": "session-evidence",
    "code": "code",
}


# Prose under a code root is commentary, not code: research notes, status
# registers, design write-ups. Calling it `code` gave it the neutral trust
# weight, and on this vault the audit register — one long Russian document that
# discusses every decision — then outranked the decision pages themselves.
_PROSE_SUFFIXES = frozenset({".md", ".markdown", ".rst", ".txt"})


def _default_source_type(candidate: _Candidate) -> str:
    if candidate.kind == "project":
        return _project_source_type(candidate)
    if candidate.kind == "code" and candidate.path.suffix.casefold() in _PROSE_SUFFIXES:
        return "doc"
    return _DEFAULT_SOURCE_TYPES[candidate.kind]


def _project_source_type(candidate: _Candidate) -> str:
    if candidate.path.name == "state.md":
        return "project-state"
    return "project-context"


def _validity_mapping(frontmatter: Mapping[str, object]) -> Mapping[str, object]:
    validity = frontmatter.get("validity", {})
    if validity is None:
        return {}
    if not isinstance(validity, Mapping):
        return {}
    return validity


def _metadata_instant(value: object) -> str | None:
    """A validity bound as text when it is an ISO date or datetime; otherwise absent."""
    text = _metadata_value(value)
    if text is None or _iso_parses(text):
        return text
    return None


def _iso_parses(text: str) -> bool:
    try:
        _parsed_iso(text)
    except ValueError:
        return False
    return True


_SCALAR_FIELDS = ("type", "project", "source_authority", "authority", "confidence", "status", "language", "lang")
_SCALAR_TYPES = (str, int, float, bool, date, datetime)


def _field_problems(mapping: Mapping[str, object]) -> list[str]:
    """Every metadata field the snapshot will ignore, named."""
    validity = mapping.get("validity")
    return _scalar_problems(mapping) + _validity_problems(validity) + _instant_problems(mapping, validity)


def _scalar_problems(mapping: Mapping[str, object]) -> list[str]:
    return [f"`{name}` is not a single value" for name in _SCALAR_FIELDS if _not_scalar(mapping.get(name))]


def _validity_problems(validity: object) -> list[str]:
    if validity is None or isinstance(validity, Mapping):
        return []
    return ["`validity` is not a mapping"]


def _instant_problems(mapping: Mapping[str, object], validity: object) -> list[str]:
    bounds = (mapping.get("valid_from"), mapping.get("valid_to"), *_validity_bounds(validity))
    return [f"`{str(value)[:40]}` is not an ISO date" for value in bounds if _not_instant(value)]


def _validity_bounds(validity: object) -> tuple[object, object]:
    if not isinstance(validity, Mapping):
        return None, None
    return validity.get("from"), validity.get("to")


def _not_scalar(value: object) -> bool:
    return value is not None and not isinstance(value, _SCALAR_TYPES)


def _not_instant(value: object) -> bool:
    return value is not None and _metadata_instant(value) is None


def frontmatter_problems(content: bytes) -> list[str]:
    """What the corpus cannot read in this page's metadata, for lint to name.

    The snapshot indexes such a page with the fields it could read; this is how
    the owner learns which fields were dropped and why.
    """
    if not _decodes_as_utf8(content):
        return ["page is not UTF-8"]
    read = read_frontmatter(content)
    if read.problem:
        return [read.problem]
    return _field_problems(read.mapping)


def _metadata_status(frontmatter: Mapping[str, object]) -> str:
    return (_metadata_value(frontmatter.get("status")) or "active").casefold()


def _metadata_language(frontmatter: Mapping[str, object]) -> str | None:
    language = _metadata_value(frontmatter.get("language") or frontmatter.get("lang"))
    if not language:
        return None
    return language.casefold()


_DAILY_DATE = re.compile(r"(\d{4}-\d{2}-\d{2})\.md$")


def _dated_by_name(candidate: _Candidate) -> str | None:
    """A daily entry's date is the one in its file name — the one certain date about it.

    Since 2026-09-09 that date is its `valid_from`, so the index's own
    since/as-of window reaches daily entries and a question's dates can bound
    a search. See `docs/research/2026-09-08-the-calendar-does-the-arithmetic.md`.
    """
    if candidate.kind != "daily":
        return None
    match = _DAILY_DATE.search(candidate.relative)
    if match is None:
        return None
    return match.group(1)


def _metadata(frontmatter: Mapping[str, object], candidate: _Candidate) -> SourceMetadata:
    validity = _validity_mapping(frontmatter)
    return SourceMetadata(
        type=_metadata_value(frontmatter.get("type")) or _default_source_type(candidate),
        project=_metadata_value(frontmatter.get("project")) or candidate.project,
        authority=_metadata_value(
            frontmatter.get("source_authority", frontmatter.get("authority"))
        ),
        confidence=_metadata_value(frontmatter.get("confidence")),
        status=_metadata_status(frontmatter),
        valid_from=_metadata_value(frontmatter.get("valid_from", validity.get("from")))
        or _dated_by_name(candidate),
        valid_to=_metadata_value(frontmatter.get("valid_to", validity.get("to"))),
        language=_metadata_language(frontmatter),
    )


def _parsed_iso(text: str) -> datetime:
    normalized = text.strip()
    if normalized.endswith("Z"):
        normalized = normalized[:-1] + "+00:00"
    try:
        return datetime.fromisoformat(normalized)
    except ValueError:
        return datetime.combine(date.fromisoformat(normalized), datetime_time.min)


def _dated_naive_datetime(value: date | datetime) -> datetime:
    if isinstance(value, datetime):
        return value
    return datetime.combine(value, datetime_time.min)


def _naive_datetime(value: str | date | datetime) -> datetime:
    if isinstance(value, (date, datetime)):
        return _dated_naive_datetime(value)
    if isinstance(value, str):
        return _parsed_iso(value)
    raise ValueError("as_of and validity values must be ISO dates or datetimes")


def _as_datetime(value: str | date | datetime | None) -> datetime | None:
    if value is None:
        return None
    result = _naive_datetime(value)
    if result.tzinfo is None:
        result = result.replace(tzinfo=timezone.utc)
    return result.astimezone(timezone.utc)


def _readable_bound(value: str | None) -> datetime | None:
    """A validity bound as an instant; one that does not parse is no bound.

    The text stays stored as written, so chunk rows do not change; only the
    reading tolerates it. See `docs/research/2026-09-14-a-bound-kept-as-written.md`.
    """
    if value is None or not _iso_parses(str(value)):
        return None
    return _as_datetime(value)


def _within_validity(metadata: SourceMetadata, instant: datetime) -> bool:
    start = _readable_bound(metadata.valid_from)
    end = _readable_bound(metadata.valid_to)
    if start is not None and start > instant:
        return False
    return end is None or instant < end


def _included(metadata: SourceMetadata, policy: SnapshotPolicy) -> bool:
    if policy.as_of is None:
        return policy.include_historical or not is_retired(metadata.status)
    instant = _as_datetime(policy.as_of)
    assert instant is not None
    return _within_validity(metadata, instant)


def _dominant(count: int, others: tuple[int, ...]) -> bool:
    return bool(count) and all(count >= other for other in others)


def _latin_only(latin: int, cyrillic: int, han: int) -> bool:
    return latin >= 3 and not cyrillic and not han


def _dominant_script_language(cyrillic: int, han: int, latin: int) -> str | None:
    if _dominant(cyrillic, (han, latin)):
        return "ru"
    if _dominant(han, (cyrillic, latin)):
        return "zh"
    return None


def _script_count(pattern: re.Pattern[str], text: str) -> int:
    """How many characters of one script the text holds, counted in C.

    `findall` builds a list of every single-character match — 10 215 lists and
    1.68 s of one cold answer on the installed vault, measured 2026-09-12, to
    produce three integers. Every class here matches exactly one character, so
    the length difference after removing them is the same count with no Python
    object per match.
    """
    return len(text) - len(pattern.sub("", text))


def _infer_language(text: str) -> str | None:
    cyrillic = _script_count(_CYRILLIC, text)
    han = _script_count(_HAN, text)
    latin = _script_count(_LATIN, text)
    dominant = _dominant_script_language(cyrillic, han, latin)
    if dominant is not None:
        return dominant
    return "en" if _latin_only(latin, cyrillic, han) else None


def _classify_language(*, explicit: str | None, path: Path, text: str) -> str | None:
    return explicit or language_for_path(path) or _infer_language(text)


def _clean_heading(raw: bytes | None) -> str:
    title = (raw or b"").decode("utf-8", errors="strict").strip()
    return _CLOSING_HASHES.sub("", title)


def _closing_fence(body: bytes, character: bytes, length: int) -> bool:
    pattern = (
        rb"[ ]{0,3}"
        + re.escape(character)
        + rb"{" + str(length).encode("ascii") + rb",}[ \t]*"
    )
    return re.fullmatch(pattern, body) is not None


def _opening_fence(body: bytes):
    """The fence that opens a block, or None — a backtick in the info string is not one."""
    opening = _FENCE.fullmatch(body)
    if opening is None:
        return None
    if opening.group(1).startswith(b"`") and b"`" in opening.group(2):
        return None
    return opening


class _HeadingScan:
    """The fence state machine that decides which lines may be headings."""

    def __init__(self) -> None:
        self.character: bytes | None = None
        self.length = 0
        self.headings: list[re.Match[bytes]] = []

    def line(self, content: bytes, offset: int, end: int) -> None:
        body = content[offset:end].rstrip(b"\r\n")
        if self.character is not None:
            self._maybe_close(body)
            return
        opening = _opening_fence(body)
        if opening is not None:
            self.character = opening.group(1)[:1]
            self.length = len(opening.group(1))
            return
        self._maybe_heading(content, offset, end)

    def _maybe_close(self, body: bytes) -> None:
        if _closing_fence(body, self.character, self.length):
            self.character = None
            self.length = 0

    def _maybe_heading(self, content: bytes, offset: int, end: int) -> None:
        heading = _HEADING.match(content, offset, end)
        if heading is None:
            return
        if len(self.headings) >= MAX_CORPUS_HEADINGS:
            raise ValueError("corpus heading row ceiling exceeded")
        self.headings.append(heading)


def _markdown_headings(
    content: bytes,
    start: int,
    *,
    deadline: float | None,
    cancelled: Callable[[], bool] | None,
) -> list[re.Match[bytes]]:
    scan = _HeadingScan()
    for offset, end in _line_spans(content, start):
        _check_processing_stop(deadline, cancelled)
        scan.line(content, offset, end)
    return scan.headings


def _headings_when_enabled(
    content: bytes,
    searchable_start: int,
    heading_enabled: bool,
    deadline: float | None,
    cancelled: Callable[[], bool] | None,
) -> list[re.Match[bytes]]:
    if not heading_enabled:
        return []
    return _markdown_headings(
        content, searchable_start, deadline=deadline, cancelled=cancelled
    )


def _leading_span(
    content: bytes, searchable_start: int, first_heading: int
) -> list[tuple[int, int, tuple[str, ...]]]:
    if content[searchable_start:first_heading].strip():
        return [(searchable_start, first_heading, ())]
    return []


def _heading_end(headings: list[re.Match[bytes]], index: int, content: bytes) -> int:
    if index + 1 < len(headings):
        return headings[index + 1].start()
    return len(content)


def _updated_ancestry(
    ancestry: list[tuple[int, str]], level: int, title: str
) -> list[tuple[int, str]]:
    kept = [item for item in ancestry if item[0] < level]
    kept.append((level, title))
    return kept


def _is_claim_ledger(content: bytes, heading: re.Match[bytes]) -> bool:
    """Whether this section is a note's claims ledger.

    Not retrievable text: one JSON line repeating claim text copied from daily logs,
    evidence references and hashes, which outranked the prose of the note a query
    was about in both lanes. Its readers — the claim index, the contradiction
    pipeline, reflection — read the page file. The `## Evidence` lines stay: they
    are the note's own claims, and the only chunk of a page that names the blocks
    `retrieval._complete_from_pages` pulls in.
    """
    return _CLAIM_LEDGER_OPENING.match(content, heading.start()) is not None


def _append_heading_span(
    spans: list, content: bytes, heading: re.Match[bytes], end: int, ancestry: list
) -> None:
    if not content[heading.start():end].strip() or _is_claim_ledger(content, heading):
        return
    if len(spans) >= MAX_CORPUS_CHUNKS:
        raise ValueError("corpus chunk row ceiling exceeded")
    spans.append((heading.start(), end, tuple(item[1] for item in ancestry)))


# A retrieval unit above this many bytes is cut at a paragraph boundary. About
# 1 024 tokens — the top of the 512–1 024 band 2026 benchmarking reports for
# analytical and multi-hop queries, taken at the top rather than the middle
# because conversational text holds a topic longer than prose does.
#
# Measured on this vault: a captured session arrives as one heading span of
# about 10 KB, roughly 2 500 tokens, against a 28 672-byte answer budget — so a
# median of two units reach the answer model, and the categories that need facts
# from more than one session score 0.0216 and 0.0988 by judge. Two and a half
# times the recommended band is not merely coarser than the reference designs;
# it is outside the range anyone reports good results in.
#
# Turn-level was the other candidate and the sources argue against it: too
# fine-grained is fragmentary, and session-level beats turn-level on its own.
# A paragraph boundary in a rendered transcript falls between speaker turns and
# between topics inside a long one, which is the closest thing to a topically
# coherent unit that costs no model call.
# See `docs/research/2026-09-02-the-unit-of-retrieval.md`.
MAX_SPAN_BYTES = 4096


def _character_boundary(content: bytes, index: int) -> int:
    """The largest index at or below `index` that begins a UTF-8 character.

    A continuation byte is `10xxxxxx`, and a character is at most four bytes,
    so walking back at most three is enough to land on a start byte.
    """
    if index >= len(content):
        return index
    floor = max(index - 3, 0)
    while index > floor and content[index] & 0xC0 == 0x80:
        index -= 1
    return index


def _paragraph_cut(content: bytes, start: int, ceiling: int) -> int:
    """The last paragraph break at or before the ceiling, then the last line.

    When a span carries neither, it is cut at the ceiling — and the ceiling is a
    byte count, so on any text that is not ASCII it lands inside a character
    about three times in four. Measured on this vault 2026-09-05: the cut fell
    at byte 4095 of a Russian paragraph, `_chunks` decoded the span strictly and
    raised, and the exception travelled all the way up through the corpus
    collector to abort the nightly generation build. Nothing was published from
    2026-08-30 onward, retrieval fell back to its lexical leg, and the only
    trace was a per-row `fallback_reason` field and one line in `doctor`.

    The two markers are ASCII and therefore already safe. It is the fallback
    that has to be walked back onto a character boundary.
    """
    window = content[start:ceiling]
    for marker in (b"\n\n", b"\n"):
        cut = window.rfind(marker)
        if cut > 0:
            return start + cut + len(marker)
    return _character_boundary(content, ceiling)


# A rendered conversation starts every turn with one of these markers at the
# start of a line. Each turn is a chunk: the user's turn is a 300-byte key that
# states the fact, and the reply it got is the value delivered beside it
# (Dense X Retrieval, arXiv:2312.06648; small-to-big retrieval). The 2026-09-02
# decision took 4 KB paragraph pieces over turns because a turn alone reads as
# a fragment; a turn is found here and read with its partner.
# See `docs/research/2026-09-08-small-keys-large-values-and-a-loop-that-stops.md`.
TURN_MARKERS = (b"**user:**", b"**assistant:**")
# A turn shorter than this stays with the turn before it: a bare "thanks" is
# not a unit worth finding on its own.
MIN_ROUND_BYTES = 160
# The user's own turns earn a chunk far sooner: they carry the facts questions ask about.
# Measured on LongMemEval 2026-09-16: of 896 evidence turns only 2 are shorter than this,
# while 4 % of all user turns are — the bare acknowledgements, which still fold.
MIN_USER_ROUND_BYTES = 48


def _marker_offsets(content: bytes, marker: bytes, start: int, end: int) -> list[int]:
    found: list[int] = []
    offset = content.find(marker, start, end)
    while offset != -1:
        found.append(offset)
        offset = content.find(marker, offset + len(marker), end)
    return found


def _begins_a_line(content: bytes, offset: int, start: int) -> bool:
    return offset > start and content[offset - 1 : offset] == b"\n"


def _round_starts(content: bytes, start: int, end: int) -> list[int]:
    """Offsets inside the span where a turn begins a line, the span's own start excluded."""
    offsets: list[int] = []
    for marker in TURN_MARKERS:
        offsets.extend(_marker_offsets(content, marker, start, end))
    return sorted(offset for offset in offsets if _begins_a_line(content, offset, start))


def _starts_a_user_turn(content: bytes, offset: int) -> bool:
    return content.startswith(TURN_MARKERS[0], offset)


def _round_bound(content: bytes, cut: int) -> int:
    """How long a round must be to earn a chunk, by whose turn begins it."""
    if _starts_a_user_turn(content, cut):
        return MIN_USER_ROUND_BYTES
    return MIN_ROUND_BYTES


def _kept_cut(content: bytes, cut: int, following: int) -> bool:
    """A stated fact begins a chunk; a bare acknowledgement folds into the round before.

    A 91-character user turn used to end a 2 101-character chunk that began with an
    assistant reply, and the fact it stated ranked 53rd. 91 % of the stand's evidence turns
    are user turns, and the reader is handed the round either way. Research:
    `docs/research/2026-09-16-a-user-turn-always-starts-its-own-chunk.md`.
    """
    return following - cut >= _round_bound(content, cut)


def _without_short_preamble(cuts: list[int], start: int) -> list[int]:
    """The heading and its stamp fold into the first round after them."""
    if not cuts or cuts[0] - start >= MIN_ROUND_BYTES:
        return cuts
    return cuts[1:]


def _long_enough_cuts(content: bytes, cuts: list[int], start: int, end: int) -> list[int]:
    """The cuts that begin a round worth finding on its own."""
    kept = _without_short_preamble(cuts, start)
    bounds = [*kept, end]
    return [cut for cut, following in zip(kept, bounds[1:]) if _kept_cut(content, cut, following)]


def _round_spans(content: bytes, span: tuple) -> list[tuple[int, int, tuple[str, ...]]]:
    """The span cut at every user turn, short rounds folded into the one before."""
    start, end, ancestry = span
    rounds: list[tuple[int, int, tuple[str, ...]]] = []
    for cut in _long_enough_cuts(content, _round_starts(content, start, end), start, end):
        rounds.append((start, cut, ancestry))
        start = cut
    rounds.append((start, end, ancestry))
    return rounds


def _split_span(content: bytes, span: tuple) -> list[tuple[int, int, tuple[str, ...]]]:
    """One span as rounds, then as bounded pieces, each keeping its heading ancestry."""
    pieces: list[tuple[int, int, tuple[str, ...]]] = []
    for round_span in _round_spans(content, span):
        pieces.extend(_bounded_pieces(content, round_span))
    return pieces


def _bounded_pieces(content: bytes, span: tuple) -> list[tuple[int, int, tuple[str, ...]]]:
    """One span as pieces of at most MAX_SPAN_BYTES, cut at paragraph boundaries."""
    start, end, ancestry = span
    pieces: list[tuple[int, int, tuple[str, ...]]] = []
    while end - start > MAX_SPAN_BYTES:
        cut = _paragraph_cut(content, start, start + MAX_SPAN_BYTES)
        if cut <= start:
            break
        pieces.append((start, cut, ancestry))
        start = cut
    pieces.append((start, end, ancestry))
    return pieces


def _bounded_spans(content: bytes, spans: list) -> list:
    bounded: list[tuple[int, int, tuple[str, ...]]] = []
    for span in spans:
        bounded.extend(_split_span(content, span))
    if len(bounded) > MAX_CORPUS_CHUNKS:
        raise ValueError("corpus chunk row ceiling exceeded")
    return bounded


def _retrieval_spans(
    content: bytes,
    searchable_start: int,
    *,
    heading_enabled: bool,
    deadline: float | None,
    cancelled: Callable[[], bool] | None,
) -> tuple[tuple[int, int, tuple[str, ...]], ...]:
    headings = _headings_when_enabled(
        content, searchable_start, heading_enabled, deadline, cancelled
    )
    first_heading = headings[0].start() if headings else len(content)
    spans = _leading_span(content, searchable_start, first_heading)
    ancestry: list[tuple[int, str]] = []
    for index, heading in enumerate(headings):
        _check_processing_stop(deadline, cancelled)
        ancestry = _updated_ancestry(
            ancestry, len(heading.group(1)), _clean_heading(heading.group(2))
        )
        _append_heading_span(
            spans, content, heading, _heading_end(headings, index, content), ancestry
        )
    return tuple(_bounded_spans(content, spans))


def _markdown_head(
    source_path: str,
    content: bytes,
    deadline: float | None,
    cancelled: Callable[[], bool] | None,
) -> tuple[bool, int, dict[str, Any]]:
    """(is markdown, where the searchable text starts, the frontmatter)."""
    is_markdown = PurePosixPath(source_path).suffix.casefold() == ".md"
    content.decode("utf-8", errors="strict")
    if not is_markdown:
        return False, 0, {}
    frontmatter, searchable_start = _frontmatter(
        content, deadline=deadline, cancelled=cancelled
    )
    return True, searchable_start, frontmatter


def canonical_retrieval_spans(
    source_path: str,
    content: bytes,
    *,
    deadline: float | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> tuple[tuple[int, int, tuple[str, ...]], ...]:
    """Return the shared canonical chunk ranges for captured source bytes."""
    if not isinstance(source_path, str) or not source_path:
        raise ValueError("source_path must be a non-empty string")
    if not isinstance(content, bytes) or len(content) > MAX_CORPUS_FILE_BYTES:
        raise ValueError("captured retrieval source must be bounded bytes")
    is_markdown, searchable_start, _frontmatter_value = _markdown_head(
        source_path, content, deadline, cancelled
    )
    return _retrieval_spans(
        content,
        searchable_start,
        heading_enabled=is_markdown,
        deadline=deadline,
        cancelled=cancelled,
    )


# One walk per source instead of two per chunk. `content.count(b"\n", 0, start)`
# rescans from byte zero for every chunk of every source, which on the installed
# vault was 11 124 scans and 1.16 s of a single 3.2 s code answer — the largest
# single cost left in it (measured 2026-09-12). The newline offsets are a fact
# about the source; taken once, each chunk's line is a binary search. The
# numbers produced are identical, which the existing chunk tests hold.
def _newline_offsets(content: bytes) -> tuple[int, ...]:
    offsets: list[int] = []
    position = content.find(b"\n")
    while position >= 0:
        offsets.append(position)
        position = content.find(b"\n", position + 1)
    return tuple(offsets)


def _line_at(offsets: tuple[int, ...], index: int) -> int:
    """The 1-based line the byte at `index` starts on."""
    return bisect_left(offsets, index) + 1


def _chunks(
    source: SourceRecord,
    metadata: SourceMetadata,
    content: bytes,
    searchable_start: int,
    *,
    heading_enabled: bool = True,
    extractor_version: str = EXTRACTOR_VERSION,
    deadline: float | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> tuple[RetrievalChunk, ...]:
    result = []
    offsets = _newline_offsets(content)
    spans = _retrieval_spans(
        content,
        searchable_start,
        heading_enabled=heading_enabled,
        deadline=deadline,
        cancelled=cancelled,
    )
    for start, end, heading_ancestry in spans:
        _check_processing_stop(deadline, cancelled)
        span = content[start:end]
        text = span.decode("utf-8", errors="strict")
        span_hash = _sha256(span)
        chunk_id = canonical_chunk_id(
            source_id=source.logical_id,
            source_path=source.relative_path,
            byte_start=start,
            byte_end=end,
            span_sha256=span_hash,
            extractor_version=extractor_version,
        )
        result.append(
            RetrievalChunk(
                id=chunk_id,
                source_id=source.logical_id,
                source_path=source.relative_path,
                parent_page=source.relative_path,
                heading_ancestry=heading_ancestry,
                byte_start=start,
                byte_end=end,
                line_start=_line_at(offsets, start),
                line_end=_line_at(offsets, end),
                text=text,
                source_sha256=source.sha256,
                span_sha256=span_hash,
                type=metadata.type,
                project=metadata.project,
                authority=metadata.authority,
                confidence=metadata.confidence,
                status=metadata.status,
                valid_from=metadata.valid_from,
                valid_to=metadata.valid_to,
                language=source.language or _infer_language(text),
            )
        )
    return tuple(result)


_SOURCE_KIND_PREFIXES = (
    (("knowledge", "raw", "sessions"), "session"),
    (("knowledge", "notes"), "note"),
    (("knowledge", "daily"), "daily"),
)


def _project_part(path: PurePosixPath) -> str | None:
    if len(path.parts) > 3:
        return path.parts[2]
    return None


def _source_kind(path: PurePosixPath) -> tuple[str, str | None]:
    for prefix, kind in _SOURCE_KIND_PREFIXES:
        if path.parts[: len(prefix)] == prefix:
            return kind, None
    if path.parts[:2] == ("knowledge", "projects"):
        return "project", _project_part(path)
    return "code", None


def _require_canonical_source(
    source_id: str,
    source_path: str,
    path: PurePosixPath,
    content: bytes,
    source_sha256: str,
) -> None:
    if not source_id or source_id != f"source:{source_path}" or not path.parts:
        raise ValueError("source identity is not canonical")
    if _sha256(content) != source_sha256:
        raise ValueError("source bytes do not match their canonical hash")


def _canonical_source_record(
    source_id: str,
    source_path: str,
    source_sha256: str,
    content: bytes,
    *,
    is_markdown: bool,
    metadata: SourceMetadata,
    candidate: _Candidate,
    searchable_start: int,
) -> SourceRecord:
    language = _classify_language(
        explicit=metadata.language,
        path=candidate.path,
        text=content[searchable_start:].decode("utf-8", errors="strict"),
    )
    return SourceRecord(
        source_id,
        source_path,
        source_sha256,
        len(content),
        "text/markdown" if is_markdown else "text/plain",
        language,
        None,
    )


def canonical_retrieval_chunks(
    *,
    source_id: str,
    source_path: str,
    source_sha256: str,
    content: bytes,
    extractor_version: str = EXTRACTOR_VERSION,
    deadline: float | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> tuple[RetrievalChunk, ...]:
    """Reconstruct every canonical chunk field from authoritative source bytes."""
    path = PurePosixPath(source_path)
    _require_canonical_source(source_id, source_path, path, content, source_sha256)
    kind, project = _source_kind(path)
    is_markdown, searchable_start, frontmatter = _markdown_head(
        source_path, content, deadline, cancelled
    )
    candidate = _Candidate(Path(*path.parts), source_path, kind, project, ())
    metadata = _metadata(frontmatter, candidate)
    source = _canonical_source_record(
        source_id,
        source_path,
        source_sha256,
        content,
        is_markdown=is_markdown,
        metadata=metadata,
        candidate=candidate,
        searchable_start=searchable_start,
    )
    return _chunks(
        source,
        metadata,
        content,
        searchable_start,
        heading_enabled=is_markdown,
        extractor_version=extractor_version,
        deadline=deadline,
        cancelled=cancelled,
    )


def _normalize_explicit_paths(
    values: Iterable[str | Path],
    normalize: Callable[[str | Path], str],
    *,
    label: str,
) -> tuple[str, ...]:
    normalized = []
    seen = set()
    for value in values:
        path = normalize(value)
        if path in seen:
            raise ValueError(f"duplicate {label}: {path}")
        seen.add(path)
        normalized.append(path)
    return tuple(sorted(normalized))


def _require_daily_files(normalized_daily: tuple[str, ...]) -> None:
    for path in normalized_daily:
        if not path.endswith(".md") or path == "knowledge/daily":
            raise ValueError("daily evidence must name an explicit Markdown file")


def _require_no_nested_root(root: str, others: tuple[str, ...]) -> None:
    for other in others:
        if other.startswith(root + "/"):
            raise ValueError(f"overlapping code roots are forbidden: {root}, {other}")


def _require_disjoint_roots(normalized_code: tuple[str, ...]) -> None:
    for index, root in enumerate(normalized_code):
        _require_no_nested_root(root, normalized_code[index + 1 :])


def _as_of_text(as_of: str | date | datetime | None) -> str | None:
    value = _metadata_value(as_of)
    if value is None:
        return None
    parsed = _as_datetime(value)
    assert parsed is not None
    return parsed.isoformat().replace("+00:00", "Z")


def _policy(
    *,
    daily_paths: Iterable[str | Path],
    code_roots: Iterable[str | Path],
    approved_code_roots: Iterable[str],
    include_historical: bool,
    as_of: str | date | datetime | None,
    max_files: int,
    max_file_bytes: int,
    max_total_bytes: int,
    max_entries: int,
    max_directories: int,
    max_depth: int,
) -> SnapshotPolicy:
    if not isinstance(include_historical, bool):
        raise ValueError("include_historical must be boolean")
    normalized_daily = _normalize_explicit_paths(
        daily_paths,
        lambda path: _relative_posix(path, prefixes=("knowledge/daily",)),
        label="daily evidence path",
    )
    _require_daily_files(normalized_daily)
    approved = tuple(sorted({str(name) for name in approved_code_roots}))
    normalized_code = _normalize_explicit_paths(
        code_roots, lambda path: _code_root(path, approved), label="code root"
    )
    _require_disjoint_roots(normalized_code)
    return SnapshotPolicy(
        daily_paths=normalized_daily,
        code_roots=normalized_code,
        include_historical=include_historical,
        as_of=_as_of_text(as_of),
        max_files=_positive_limit(max_files, "max_files"),
        max_file_bytes=_positive_limit(max_file_bytes, "max_file_bytes"),
        max_total_bytes=_positive_limit(max_total_bytes, "max_total_bytes"),
        max_entries=_positive_limit(max_entries, "max_entries"),
        max_directories=_positive_limit(max_directories, "max_directories"),
        max_depth=_positive_limit(max_depth, "max_depth", allow_zero=True),
    )


def _candidate_content(candidate: _Candidate, policy: SnapshotPolicy, label: str) -> bytes:
    if candidate.content is not None:
        return candidate.content
    _verify_seal(candidate.seal)
    content = _sealed_source_bytes(candidate.path, policy.max_file_bytes, label)
    _verify_seal(candidate.seal)
    return content


def _sealed_source_bytes(path: Path, max_bytes: int, label: str) -> bytes:
    """A source read by path, where a file being written is a changed corpus.

    This is the reader where directory descriptors are not available. The
    descriptor walk already calls a file that moves under it `CorpusChanged`,
    which is retried and then named; here the same event arrived as a bare
    `PermissionError`, so the capture died on the first write and the refusal
    blamed the repository's size. Research:
    `docs/research/2026-09-17-five-failures-only-the-other-systems-showed.md`.
    """
    try:
        return read_stable_bytes(path, max_bytes, label=label)
    except SourceChangedDuringRead as error:
        raise CorpusChanged(f"corpus source changed during read: {path.name}") from error


def _captured_record(
    candidate: _Candidate,
    content: bytes,
    metadata: SourceMetadata,
    is_markdown: bool,
    searchable_start: int,
    digest: str,
) -> SourceRecord:
    language = _classify_language(
        explicit=metadata.language,
        path=candidate.path,
        text=content[searchable_start:].decode("utf-8", errors="strict"),
    )
    return SourceRecord(
        logical_id=f"source:{candidate.relative}",
        relative_path=candidate.relative,
        sha256=digest,
        size=len(content),
        media_type="text/markdown" if is_markdown else "text/plain",
        language=language,
        git_oid=None,
    )


class _Capture:
    """Accumulates captured sources and their chunks under the policy limits."""

    def __init__(
        self,
        policy: SnapshotPolicy,
        deadline: float,
        cancelled: Callable[[], bool] | None,
    ) -> None:
        self.policy = policy
        self.deadline = deadline
        self.cancelled = cancelled
        self.captured: list[CapturedSource] = []
        self.chunks: list[RetrievalChunk] = []
        self.hashes: dict[str, str] = {}
        self.total = 0

    def add(self, candidate: _Candidate) -> None:
        content = _candidate_content(candidate, self.policy, "corpus source")
        self._count_bytes(len(content))
        is_markdown = candidate.path.suffix.casefold() == ".md"
        # A page that is not text costs itself, as any other undecodable file does.
        readable = _decodes_as_utf8(content)
        frontmatter, searchable_start = self._head(content, is_markdown and readable)
        metadata = _metadata(frontmatter, candidate)
        digest = _sha256(content)
        self.hashes[candidate.relative] = digest
        if readable and _included(metadata, self.policy):
            self._store(candidate, content, metadata, is_markdown, searchable_start, digest)

    def _head(self, content: bytes, is_markdown: bool) -> tuple[dict[str, Any], int]:
        if not is_markdown:
            return {}, 0
        return _frontmatter(content, deadline=self.deadline, cancelled=self.cancelled)

    def _count_bytes(self, size: int) -> None:
        self.total += size
        if self.total > self.policy.max_total_bytes:
            raise ValueError("corpus total byte limit exceeded")

    def _store(
        self,
        candidate: _Candidate,
        content: bytes,
        metadata: SourceMetadata,
        is_markdown: bool,
        searchable_start: int,
        digest: str,
    ) -> None:
        record = _captured_record(
            candidate, content, metadata, is_markdown, searchable_start, digest
        )
        self.captured.append(CapturedSource(record, metadata, content))
        source_chunks = _chunks(
            record,
            metadata,
            content,
            searchable_start,
            heading_enabled=is_markdown,
            deadline=self.deadline,
            cancelled=self.cancelled,
        )
        if len(self.chunks) + len(source_chunks) > MAX_CORPUS_CHUNKS:
            raise ValueError("corpus chunk row ceiling exceeded")
        self.chunks.extend(source_chunks)


def _require_stable_membership(
    candidates: tuple[_Candidate, ...], current: tuple[_Candidate, ...]
) -> None:
    if tuple(item.relative for item in candidates) != tuple(
        item.relative for item in current
    ):
        raise CorpusChanged("corpus membership changed during collection")


def _require_stable_content(
    current: tuple[_Candidate, ...],
    policy: SnapshotPolicy,
    hashes: dict[str, str],
    deadline: float,
) -> None:
    for candidate in current:
        _check_deadline(deadline)
        content = _candidate_content(candidate, policy, "corpus validation source")
        if _sha256(content) != hashes[candidate.relative]:
            raise CorpusChanged(
                f"corpus source changed during collection: {candidate.relative}"
            )


def _capture(
    vault: Path,
    policy: SnapshotPolicy,
    deadline: float,
    cancelled: Callable[[], bool] | None,
) -> CorpusSnapshot:
    candidates = _discover(vault, policy, deadline)
    capture = _Capture(policy, deadline, cancelled)
    for candidate in candidates:
        _check_deadline(deadline)
        capture.add(candidate)
    _check_deadline(deadline)
    current = _discover(vault, policy, deadline)
    _require_stable_membership(candidates, current)
    _require_stable_content(current, policy, capture.hashes, deadline)
    corpus_hash = canonical_source_manifest_sha256(
        (source.record for source in capture.captured), policy
    )
    return CorpusSnapshot(
        tuple(capture.captured), tuple(capture.chunks), corpus_hash, policy
    )


# A capture reads every source, then re-reads every source and refuses the
# snapshot if anything moved. That fence is right and stays: it is what proves a
# published generation describes a moment the vault really passed through.
#
# What was wrong was surrendering the first time it fired. Measured 2026-09-05: a
# pass costs 3.5-3.6 seconds and never fails on a quiet vault, but a session
# appends to today's daily log on every tool call, so under maintenance the pass
# loses the race and the whole nightly build died with it — every night from
# 2026-08-30, leaving no active generation and retrieval on its lexical leg
# alone. Nothing about the fence changed; the vault outgrew it.
#
# Snapshot isolation, in every MVCC engine, means a consistent view from the
# point a transaction started — not a world that holds still until it commits.
# So: take another pass. Fail only if the vault never holds still for one.
MAX_CAPTURE_PASSES = 4


def _captured_after_retries(
    root: Path,
    policy: SnapshotPolicy,
    deadline: float,
    cancelled: Callable[[], bool] | None,
) -> CorpusSnapshot:
    """One capture that describes a real instant, retried while the vault moves."""
    last: CorpusChanged | None = None
    for _ in range(MAX_CAPTURE_PASSES):
        _check_processing_stop(deadline, cancelled)
        try:
            return _capture(root, policy, deadline, cancelled)
        except CorpusChanged as exc:
            last = exc
    raise CorpusChanged(f"corpus never held still for one pass: {last}")


def collect_corpus(
    vault: Path,
    *,
    daily_paths: Iterable[str | Path] = (),
    code_roots: Iterable[str | Path] = (),
    approved_code_roots: Iterable[str] = APPROVED_CODE_ROOTS,
    include_historical: bool = False,
    as_of: str | date | datetime | None = None,
    max_files: int = MAX_CORPUS_FILES,
    max_file_bytes: int = MAX_CORPUS_FILE_BYTES,
    max_total_bytes: int = MAX_CORPUS_TOTAL_BYTES,
    max_entries: int = MAX_CORPUS_INSPECTED_ENTRIES,
    max_directories: int = MAX_CORPUS_DIRECTORIES,
    max_depth: int = MAX_CORPUS_DEPTH,
    deadline: float | None = None,
    deadline_seconds: float | None = None,
    coordinator: object | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> CorpusSnapshot:
    """Capture one immutable corpus and reject any change before returning it."""
    root = Path(vault).resolve(strict=True)
    if not stat.S_ISDIR(_safe_info(root).st_mode):
        raise ValueError("vault must be a regular directory")
    selected_policy = _policy(
        daily_paths=daily_paths,
        code_roots=code_roots,
        approved_code_roots=approved_code_roots,
        include_historical=include_historical,
        as_of=as_of,
        max_files=max_files,
        max_file_bytes=max_file_bytes,
        max_total_bytes=max_total_bytes,
        max_entries=max_entries,
        max_directories=max_directories,
        max_depth=max_depth,
    )
    selected_deadline = _deadline_value(deadline, deadline_seconds)
    if coordinator is not None:
        _check_deadline(selected_deadline)
        remaining = max(0.0, selected_deadline - time.monotonic())
        gate = coordinator.writer_gate(wait_seconds=remaining)
    else:
        gate = contextlib.nullcontext()
    with gate:
        _check_processing_stop(selected_deadline, cancelled)
        return _captured_after_retries(
            root, selected_policy, selected_deadline, cancelled
        )


def validate_live_snapshot(
    snapshot: CorpusSnapshot,
    vault: Path,
    *,
    daily_paths: Iterable[str | Path] | None = None,
    code_roots: Iterable[str | Path] | None = None,
    include_historical: bool | None = None,
    as_of: str | date | datetime | None = None,
    max_files: int | None = None,
    max_file_bytes: int | None = None,
    max_total_bytes: int | None = None,
    max_entries: int | None = None,
    max_directories: int | None = None,
    max_depth: int | None = None,
    deadline: float | None = None,
    deadline_seconds: float | None = None,
    coordinator: object | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> None:
    """Refuse a snapshot that does not describe itself, immediately before publication.

    This used to re-collect the entire live corpus and demand it be byte-identical
    to the snapshot taken minutes earlier. That asks the vault to hold still for
    the length of a build, which no vault in use ever does — and measured on this
    one, none has since 2026-08-30. Every nightly build died here, nothing was
    activated, and retrieval fell back to its lexical leg for five days while the
    complete vectors sat unreachable on disk.

    A snapshot is a snapshot. Snapshot isolation, in every MVCC engine, means a
    consistent view from the point a read started, not a world frozen until it
    commits; Lucene commits are point-in-time for the same reason. What a
    published generation owes its readers is that it describes a moment the vault
    really passed through — which the collection fence already proves, twice,
    before this is ever called.

    What it does not owe them is being the newest moment. A document written
    after the snapshot is absent until the next build, and no check here could
    find it: there is nothing yet to check. That is the price of a lagging index
    and it is the only one we pay, because a source the vault has since moved on
    from is re-read and dropped before its text can reach the model — see
    `query_memory._FreshSources`.

    So what is verified here is that the snapshot is what it says it is: its
    sources still hash to the manifest recorded in `corpus_sha256`. That is
    tamper-evidence, it costs no I/O, and it removes a second full collection
    from every publication.
    """
    if not isinstance(snapshot, CorpusSnapshot):
        raise TypeError("snapshot must be a CorpusSnapshot")
    recomputed = canonical_source_manifest_sha256(
        (source.record for source in snapshot.sources), snapshot.policy
    )
    if recomputed != snapshot.corpus_sha256:
        raise CorpusChanged("snapshot does not match its own source manifest")
