"""Regenerate `knowledge/index.md` from `knowledge/notes/**/*.md`, and the project pages.

Supports both flat notes (current public layout) and typed subdirs
(concepts/decisions/patterns/debugging/qa) when present. The project pages
(`project_pages`) are private and derived from the same notes, so they are
regenerated in the same transaction; the tracked index never names them.
"""
from __future__ import annotations

import re
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from bounded_io import MAX_KNOWLEDGE_PAGE_BYTES, read_stable_bytes  # noqa: E402
from claim_tree_manifest import snapshot_claim_tree_with_content  # noqa: E402
from markdown_transaction import (  # noqa: E402
    ABSENT,
    TransactionDriftError,
    TransactionFailure,
    mutate_knowledge,
    stable_operation_id,
)
from memory_state import ROOT  # noqa: E402
from page_status import is_retired  # noqa: E402
from project_map import MAP_RELATIVE_PATH  # noqa: E402
from project_pages import page_writes  # noqa: E402
from reliable_memory import canonical_json_bytes, sha256_bytes  # noqa: E402

memory = ROOT / "knowledge"
knowledge = memory / "notes"
out = memory / "index.md"

TYPE_SECTIONS = {
    "concept": "Concepts",
    "decision": "Decisions",
    "pattern": "Patterns",
    "debugging": "Debugging",
    "qa": "Q&A",
    "entity": "Entities",
    "synthesis": "Syntheses",
    "comparison": "Comparisons",
    "connection": "Connections",
    "workflow": "Workflows",
    "raw-source": "Raw sources",
}

SUMMARY_RE = re.compile(r"^One-sentence summary:\s*(.+?)\s*$", re.MULTILINE)
TYPE_RE = re.compile(r"^type:\s*(.+?)\s*$", re.MULTILINE)
STATUS_RE = re.compile(r"^status:\s*(.+?)\s*$", re.MULTILINE)
SKIP_NAMES = {"README.md", "index.md", "log.md"}
MAX_PAGE_BYTES = MAX_KNOWLEDGE_PAGE_BYTES
# `knowledge/index.md` as this module writes it and the compile reads it back.
MAX_INDEX_BYTES = 4 * 1024 * 1024
MAX_PAGE_COUNT = 2_000
MAX_TOTAL_PAGE_BYTES = 32 * 1024 * 1024
MAX_REBUILD_ATTEMPTS = 4


INDEX_HEADER = (
    "# Session Memory Index",
    "",
    "This index catalogs durable memory distilled from AI agent sessions",
    "(OpenCode, Codex, Claude Code).",
    "",
    "## Entry points",
    "- `docs/operating-model.md` — compile cadence, promotion rules, and the daily ↔ notes boundary.",
    "- Recent daily logs live under `knowledge/daily/` — raw, timestamped session captures awaiting compile.",
    "",
)

INDEX_FOOTER = (
    "## Editorial note",
    "This index is vault metadata — a navigation map over `knowledge/notes/`, not a page derived from `raw/` or `inbox/`. It is regenerated by `scripts/rebuild_memory_index.py`; edits to page titles or one-sentence summaries will be picked up on the next rebuild.",
)

NOTES_PREFIX = "knowledge/notes/"
NOTES_DENIAL = f"{NOTES_PREFIX}*"


def build_index_bytes(
    root: Path = ROOT,
    pending: Mapping[str, bytes | None] | None = None,
    *,
    base: Mapping[str, bytes] | None = None,
) -> bytes:
    """Render the index from disk plus unpublished transaction after-images."""
    root = Path(root)
    virtual = _virtual_pages(root, base)
    _require_within_limits(virtual)
    _apply_pending(virtual, pending)
    _require_within_limits(virtual)
    return _render_index(_index_buckets(_published_only(root, virtual)))


def _virtual_pages(
    root: Path, base: Mapping[str, bytes] | None
) -> dict[str, bytes]:
    if base is not None:
        return dict(base)
    notes = root / "knowledge" / "notes"
    if not notes.exists():
        return {}
    return {
        path.relative_to(root).as_posix(): read_stable_bytes(
            path, MAX_PAGE_BYTES, label="knowledge index source"
        )
        for path in notes.rglob("*.md")
    }


def _require_within_limits(virtual: Mapping[str, bytes]) -> None:
    if len(virtual) > MAX_PAGE_COUNT:
        raise ValueError("knowledge index page count exceeds limit")
    if sum(len(content) for content in virtual.values()) > MAX_TOTAL_PAGE_BYTES:
        raise ValueError("knowledge index source bytes exceed limit")


def _apply_pending(
    virtual: dict[str, bytes], pending: Mapping[str, bytes | None] | None
) -> None:
    for relative, content in (pending or {}).items():
        if not relative.startswith("knowledge/notes/"):
            raise ValueError("pending index path is outside knowledge notes")
        _apply_one_pending(virtual, relative, content)


def _apply_one_pending(
    virtual: dict[str, bytes], relative: str, content: bytes | None
) -> None:
    if content is None:
        virtual.pop(relative, None)
        return
    if len(content) > MAX_PAGE_BYTES:
        raise ValueError("pending index page exceeds limit")
    virtual[relative] = content


def _published_only(root: Path, virtual: dict[str, bytes]) -> dict[str, bytes]:
    """Drop the pages this repository does not publish.

    The vault and the public source are one directory and `knowledge/index.md`
    is tracked, so a private page's title reaching the index would put it in a
    public file.
    """
    named, _hidden = published_paths(root, sorted(virtual))
    keep = set(named)
    return {path: content for path, content in virtual.items() if path in keep}


def _published_notes(root: Path) -> set[str] | None:
    """The notes .gitignore un-ignores, or None when it denies none of them.

    Read rather than asked of git: the index rebuild is an automatic writer, and
    no automatic writer here runs git. This repository publishes by an exact `!`
    line per page — its own comment forbids a broad `!*.md` — so the file says
    exactly what is public. A vault whose .gitignore does not deny the notes
    directory is not a public repository, and nothing is filtered.
    """
    lines = _gitignore_lines(root)
    if NOTES_DENIAL not in lines:
        return None
    return {line[1:] for line in lines if line.startswith(f"!{NOTES_PREFIX}")}


def published_paths(root: Path, paths: Sequence[str]) -> tuple[list[str], int]:
    """Split paths into the ones this repository publishes and a count of the rest.

    `knowledge/log.md` is tracked in the public source and the compile pass
    appends the pages it touched to it, so a private slug written there is
    personal content in a public file. A vault whose `.gitignore` denies
    nothing publishes everything, and nothing is filtered.
    """
    denials, allowed = _publication_rules(root)
    if not denials:
        return list(paths), 0
    named = [item for item in paths if _is_public_path(item, denials, allowed)]
    return named, len(paths) - len(named)


def _publication_rules(root: Path) -> tuple[set[str], set[str]]:
    """Denied directory prefixes, and the exceptions that publish again.

    A denial covers a directory; an exception names one exact file, or one
    directory when it ends in a slash. Reading an exception as a prefix would
    publish every sibling of the one page that was allowed.
    """
    denials: set[str] = set()
    allowed: set[str] = set()
    for line in _gitignore_lines(root):
        _classify_rule(line, denials, allowed)
    return {item for item in denials if item}, allowed


def _classify_rule(line: str, denials: set[str], allowed: set[str]) -> None:
    if line.startswith("!"):
        allowed.add(line[1:])
        return
    denials.add(_rule_prefix(line))


def _rule_prefix(rule: str) -> str:
    """A rule covers the directory it names; `notes/*.md` covers `notes/`."""
    head, separator, _tail = rule.rpartition("/")
    if not separator:
        return ""
    return f"{head}/"


def _is_public_path(path: str, denials: set[str], allowed: set[str]) -> bool:
    if not any(path.startswith(prefix) for prefix in denials):
        return True
    if path in allowed:
        return True
    return _under_allowed_directory(path, allowed)


def _under_allowed_directory(path: str, allowed: set[str]) -> bool:
    directories = [item for item in allowed if item.endswith("/")]
    return any(path.startswith(item) for item in directories)


def _gitignore_lines(root: Path) -> set[str]:
    try:
        text = (root / ".gitignore").read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return set()
    return {line.strip() for line in text.splitlines() if line.strip()}


def _index_buckets(virtual: Mapping[str, bytes]) -> dict[str, list[tuple[str, str]]]:
    buckets: dict[str, list[tuple[str, str]]] = {
        name: [] for name in TYPE_SECTIONS.values()
    }
    buckets["Other"] = []
    for relative, raw in sorted(virtual.items()):
        entry = _index_entry(relative, raw)
        if entry is None:
            continue
        section, link, summary = entry
        buckets[section].append((link, summary))
    return buckets


def _index_entry(relative: str, raw: bytes) -> tuple[str, str, str] | None:
    """Section, link and summary for a page, or None when it does not belong."""
    if _excluded_from_index(relative):
        return None
    text = raw.decode("utf-8", errors="strict")
    if _is_retired(text):
        return None
    return _section_of(text), _index_link(relative), _summary_of(text)


def _excluded_from_index(relative: str) -> bool:
    if Path(relative).name in SKIP_NAMES:
        return True
    return "/archive/" in f"/{relative}/"


def _is_retired(text: str) -> bool:
    status = STATUS_RE.search(text)
    if status is None:
        return False
    return is_retired(status.group(1))


def _section_of(text: str) -> str:
    page_type = TYPE_RE.search(text)
    if page_type is None:
        return "Other"
    return TYPE_SECTIONS.get(page_type.group(1).strip().strip("\"'"), "Other")


def _index_link(relative: str) -> str:
    """A bare `[[slug]]`, which Obsidian resolves from anywhere in the vault."""
    return Path(relative).stem


def _summary_of(text: str) -> str:
    summary = SUMMARY_RE.search(text)
    if summary is None:
        return ""
    return summary.group(1).strip()


def _render_index(buckets: Mapping[str, list[tuple[str, str]]]) -> bytes:
    lines = list(INDEX_HEADER)
    for name in [*TYPE_SECTIONS.values(), "Other"]:
        lines.extend(_section_lines(name, buckets.get(name, [])))
    lines.extend(INDEX_FOOTER)
    output = ("\n".join(lines).rstrip() + "\n").encode("utf-8")
    if len(output) > MAX_INDEX_BYTES:
        raise ValueError("knowledge index output exceeds limit")
    return output


def _section_lines(name: str, entries: list[tuple[str, str]]) -> list[str]:
    pages = sorted(set(entries), key=lambda item: item[0].casefold())
    if not pages:
        return []
    return [f"## {name}", *(_page_line(*page) for page in pages), ""]


def _page_line(link: str, summary: str) -> str:
    if not summary:
        return f"- [[{link}]]"
    return f"- [[{link}]] — {summary}"


def main() -> int:
    repair_lineage = ""
    for _ in range(MAX_REBUILD_ATTEMPTS):
        plan = _rebuild_plan(repair_lineage)
        if plan is None:
            print("rebuild_memory_index: knowledge/index.md is current")
            return 0
        operation_id, changes, preconditions = plan
        try:
            mutate_knowledge(operation_id, changes, preconditions=preconditions)
            _report(changes)
            return 0
        except TransactionDriftError as exc:
            repair_lineage = exc.transaction_id
        except (TransactionFailure, ValueError) as exc:
            _require_retryable(exc)
    raise RuntimeError("knowledge index rebuild did not converge")


def _report(changes: Mapping[Path, bytes | None]) -> None:
    for path, content in changes.items():
        relative = Path(path).relative_to(ROOT).as_posix()
        if content is None:
            print(f"rebuild_memory_index: {relative} removed")
        else:
            print(f"rebuild_memory_index: {relative} rebuilt ({len(content)} bytes)")


def _rebuild_plan(
    repair_lineage: str,
) -> tuple[str, dict[Path, bytes | None], dict[str, object]] | None:
    """The writes to make, or None when the index and project pages match the vault."""
    manifest, tree = snapshot_claim_tree_with_content(ROOT)
    notes = {
        path: content
        for path, content in tree.items()
        if path.startswith("knowledge/notes/")
    }
    content = build_index_bytes(ROOT, base=notes)
    before_bytes, before_hash = _current_index()
    changes: dict[Path, bytes | None] = {}
    if before_bytes != content:
        changes[out] = content
    preconditions: dict[str, object] = {
        "claim_tree_manifest": manifest,
        out.relative_to(ROOT).as_posix(): before_hash,
    }
    pages = page_writes(ROOT, notes=notes)
    for page in pages:
        changes[ROOT / page.path] = page.content
        preconditions[page.path] = page.before
    if pages:
        preconditions[MAP_RELATIVE_PATH] = _current_hash(ROOT / MAP_RELATIVE_PATH)
    if not changes:
        return None
    generation = str(manifest["absence_generation"])
    written = canonical_json_bytes(
        {
            Path(path).relative_to(ROOT).as_posix(): None if data is None else sha256_bytes(data)
            for path, data in changes.items()
        }
    )
    return (
        stable_operation_id(
            "rebuild-index", f"{generation}:{before_hash}:{repair_lineage}", written
        ),
        changes,
        preconditions,
    )


def _current_hash(path: Path) -> str:
    try:
        return sha256_bytes(read_stable_bytes(path, MAX_PAGE_BYTES, label="project map"))
    except FileNotFoundError:
        return ABSENT


def _current_index() -> tuple[bytes | None, str]:
    try:
        before_bytes = read_stable_bytes(
            out, MAX_INDEX_BYTES, label="knowledge index before-state"
        )
    except FileNotFoundError:
        return None, ABSENT
    return before_bytes, sha256_bytes(before_bytes)


def _require_retryable(exc: BaseException) -> None:
    """A precondition that moved under us is a retry; anything else is not."""
    if isinstance(exc, TransactionFailure) and exc.code == "precondition_failed":
        return
    if isinstance(exc, ValueError) and _is_precondition_drift(exc):
        return
    raise exc


def _is_precondition_drift(exc: ValueError) -> bool:
    return "caller precondition does not match target" in str(exc)


if __name__ == "__main__":
    raise SystemExit(main())
